### ISSUE TITLE
Different output folder

### ISSUE THREAD

**Issue by raonyguimaraes** [sigven/pcgr#1]
Hi there,
Thanks for this excellent tool!!!

Would be nice to be able to direct the output to a different folder. I like to have a better separation between input and output data.

Keep up the good work! 

Kind Regards.

**Comment by sigven** [comment]
Hi, 

Thanks for the feedback. In the latest release (v0.3) I have enabled more flexible separation of input and output. Let me know if you run into problems. Thanks for the suggestion!

best,
Sigve
