### ISSUE TITLE
database of tcga seems to be incomplete

### ISSUE THREAD

**Issue by gudeqing** [sigven/pcgr#100]
Hi,
   I found the database of tcga from "grch37 data bundle - 20191116" is likely to be incomplete as only chromosome of 1-6 are included. The same situation also applies to grch38. So, would please check the completeness of the source data?
   Best Regards!

**Comment by sigven** [comment]
hi @gudeqing,
thanks a lot for your observation. I'll have a look and get back to you.
thanks,
Sigve

**Comment by sigven** [comment]
You are correct, thanks a lot for observing this.I will both

1) add a link to the complete VCF, so users can make the latest bundle complete
2) implement a routine that checks for completeness in the data generation, preventing similar things to happen in future releases

thanks again,
Sigve
