### ISSUE TITLE
Preprocess Error

### ISSUE THREAD

**Issue by xgnusr** [sigven/pcgr#101]
Hi,
I have detected that in grch37 this error occurs:

2020-01-09 11:26:31 - pcgr-validate-input - WARNING - Multiallelic site detected:chrUn_gl000245 3356    C       A,G
2020-01-09 11:26:31 - pcgr-validate-input - WARNING - Multiallelic site detected:chrUn_gl000246 37528   G       C,T
2020-01-09 11:26:31 - pcgr-validate-input - WARNING - Multiallelic site detected:chrUn_gl000246 37804   T       A,G
2020-01-09 11:27:03 - pcgr-validate-input - INFO - Decomposing multi-allelic sites in input VCF file using 'vt decompose'
**[E::hts_idx_push] Chromosome blocks not continuous
tbx_index_build failed: /home/nemo/z.ensayos/111.pcgr_ready.vcf.gz**
[W::vcf_parse] Contig '1_gl000192_random' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1_gl000191_random' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '2' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '3' is not defined in the header. (Quick workaround: index the file with tabix.)

Any ideas about it?
Very thanks !!

**Comment by sigven** [comment]
Dear @xgnusr,
Try to compress and index your VCF file before submitting for analysis (bgzip + tabix). This step will succeed if your VCF file is sorted (chrosomal and positional) properly.

best,
Sigve

**Comment by xgnusr** [comment]
Dear Sigve,
The problem remains the same after compressing and indexing (bgzip + tabix)
Suggestions ?
Very thanks !!

**Comment by sigven** [comment]
Can you share your VCF file with me to have a look (Dropbox etc)?

Sigve

**Comment by xgnusr** [comment]
Sure !!
Can you send me an email address to ensure the confidentiality of the data?

Thank you !!

**Comment by sigven** [comment]
sigven AT ifi.uio.no

**Comment by sigven** [comment]
Hi @xgnusr,

A couple of comments regarding your file.

1) It seems your VCF comes from germline variant calling (GATK HaplotypeCaller).  This is not intended input for PCGR. PCGR is intended for somatic mutation profiling (i.e. it accepts somatic variants,  as detected through tumor-normal sequencing and subsequent variant calling (MuTect2, Strelka2, SomaticSniper etc)). Somatic VCF files are frequently much smaller (lower number of calls) than the one you are looking into.

2) Although PCGR decomposes multi-allelic calls, this procedure is not bullet-proof, so I generally recommend a VCF with single allele calls as input for PCGR (meaning that you should look into how this can performed upstream of running the PCGR workflow).

regards,
Sigve
