### ISSUE TITLE
STEP4 error

### ISSUE THREAD

**Issue by xgnusr** [sigven/pcgr#102]
Hi Sigven,
possible incomplete installation for grch37?
Thanks,
Fco.

2020-01-18 05:44:18 - pcgr-writer - INFO - STEP 4: Generation of output files - variant interpretation report for precision oncology
Error in library(BSgenome.Hsapiens.UCSC.hg19) :
  there is no package called ‘BSgenome.Hsapiens.UCSC.hg19’
Execution interrupted

**Comment by sigven** [comment]
Hi,
Seems strange. Are you using the Dockerized version (and which PCGR version are you using)?

**Comment by xgnusr** [comment]
Hi Segven,

I am using the version installed by conda, in its own environment.
any ideas ?

Thank you !

**Comment by xgnusr** [comment]
Good morning,
After downloading and re-installing, everything works fine until:

2020-01-26 18:34:41 [INFO] Writing JSON file with report contents
Error in collapse(tmp, inner = FALSE, indent = indent) :
  R character strings are limited to 2^31-1 bytes
Calls: <Anonymous> ... .local -> vapply -> FUN -> FUN -> .local -> collapse
Execution interrupted

**Comment by sigven** [comment]
I see. This appears to be an issue with R's memory limitations, and probably linked to the size of the input data. What is the size of your input VCF? Or how many variants does it contain?

**Comment by sigven** [comment]
Feel free to open if I can get more details on your query. Closing for now.
