### ISSUE TITLE
Specific naming of required arguments

### ISSUE THREAD

**Issue by brucemoran** [sigven/pcgr#103]
Hi Sigve,

a basic request, could you allow `--pcgr_dir`, `--output_dir`, `--genome_assembly`, `--configuration_file`, `--sample_id` (or similar) naming structure for required inputs? 

Reasoning is that it is more straightforward than un-named and positionally determined inputs.

Thanks,

Bruce

**Comment by sigven** [comment]
Hi Bruce,

Good point, indeed. Been moving in that direction with other things, so I am all for this. Will add this as an enhancement for next release.

Thanks for your suggestion,

Sigve

**Comment by brucemoran** [comment]
Great!
