### ISSUE TITLE
Database Election is it possible?

### ISSUE THREAD

**Issue by ngslabex** [sigven/pcgr#104]
Hi sigven,
Can I select databases which i want? 
For example i want to ignore CIViC database.
Or,
Can i add weight value for database to calculate predictions?
For example; COSMIC database is more important from CIViC database.
Thanks.

**Comment by ngslabex** [comment]
How do you calculate the situation that any variant there is in COSMIC but not in CIViC? is CIViC added the calculation if there is no record?

**Comment by sigven** [comment]
Hi @ngslabex,

Thanks for your email. Afraid this is not possible. Please note that the main purpose of PCGR is to integrate knowledge resources and provide measures as to interpret the spectrum of tumor variants for clinical purposes. In this regard, CIViC is far more important than COSMIC, the latter providing an indication as to the frequency of different somatic variants across tissues and samples. I do agree that the overlap of the query variant set with what is present in COSMIC could be visualized/presented better. I will add this for future developments. 

Meanwhile, if you care mostly about how your variant set overlaps with COSMIC, and believe this is the most valuable resource, consider the output TSV file (which contains the COSMIC ID's for variants) and process/rank them in whatever way you see fit.

best,
Sigve
