### ISSUE TITLE
Custom vep flags

### ISSUE THREAD

**Issue by ridwan-shaikh** [sigven/pcgr#109]
Hi Sigve,

I was wondering if it possible to add custom vep flags whilst running PCGR?

Regards,
Ridwan

**Comment by sigven** [comment]
Hi Ridwan,

In principle it should work, just need to make sure the output from VEP does not mess up any internal annotations from PCGR. Did you think of any specific flags? I am trying to append as much as possible from VEP, but custom annotations with e.g. external data tracks will be somewhat difficult I believe.

regards,
Sigve

**Comment by ridwan-shaikh** [comment]
Hey Sigve,

I was thinking --per-gene. From the description, i hope it would give a new line per gene of a variant rather than condensing down to one?

The following variant: NF1 chr17:29652873 c.4872dupA after annotation with VEP ends up being an EVI2A variant 17:g.29652873T>TA. I've tried to play around the the --pick-order but that doesn't seem to help. The NF1 variant is seen in the tiering .tsv file under VEP_ALL_CSQ as the frameshift mutation it should be but because it is under VEP_ALL_CSQ, it does not get the right HGVSc annotation.

**Comment by ridwan-shaikh** [comment]
Hey Sigve,

Just to let you know, for testing purposes i tried to add --per_gene to line 713 of pcgr.py and got the following error whist attempting a test run. 

```{shell}
2020-03-09 14:56:22 - pcgr-summarise - INFO - STEP 3: Cancer gene annotations with pcgr-summarise
Traceback (most recent call last):
  File "/home/DMP/DUDMP/transgen-mdx/.conda/envs/pcgr/bin/pcgr_summarise.py", line 150, in <module>
    if __name__=="__main__": __main__()
  File "/home/DMP/DUDMP/transgen-mdx/.conda/envs/pcgr/bin/pcgr_summarise.py", line 33, in __main__
    extend_vcf_annotations(args.vcf_file, args.pcgr_db_dir, logger, args.pon_annotation, args.cpsr)
  File "/home/DMP/DUDMP/transgen-mdx/.conda/envs/pcgr/bin/pcgr_summarise.py", line 120, in extend_vcf_annotations
    record = vep_csq_records[block_idx]
IndexError: list index out of range
```

**Comment by sigven** [comment]
Hi Ridwan,

Coming back to this, I suggest you play further with `--pick-order`, e.g. moving _rank_ to the front of your list. I think this would be my best solution for this. But keep in mind that changing the order may affect other variants towards unwanted behaviour, so this is complex matters.

regards,
Sigve
