### ISSUE TITLE
Output VCF missing FORMAT column

### ISSUE THREAD

**Issue by sa9** [sigven/pcgr#111]
I hope everyone is safe in these difficult times!

I noticed the output VCF files are missing FORMAT and SAMPLE columns (number 9 and 10), both are in the input VCF file. Am I missing somthing? Is there away to force wrinting them?

**Comment by sigven** [comment]
Hi @sa9,
All is well with me, hope all is well with you too:-). You are right, the VCF format parts (columns 9 and 10) of the input VCF are removed at the initial stage of PCGR as this is not used in any downstream output/processing. We have [frequently encountered](https://pcgr.readthedocs.io/en/latest/input.html#vcf) that variant callers produce erroneously formatted output in these columns (in the sense that they not adhere strictly to the VCF format, both type-wise and in terms of number of elements), and that will lead to a crash of the PCGR VCF parser. So far, PCGR thus asks the user to move information related to sequencing depth and allelic fraction to the INFO column, see [configuration](https://pcgr.readthedocs.io/en/latest/input.html#pcgr-configuration-file). If you really need information in the FORMAT/SAMPLE columns in your output, I advice you to either **a)** move them to the INFO column and append them to the output with the *custom_tags* parameter in the configuration, or **b)** append them to the output in a post-PCGR processing step.

thanks,
Sigve
