### ISSUE TITLE
vcf format for PON

### ISSUE THREAD

**Issue by ridwan-shaikh** [sigven/pcgr#112]
Hi Sigve,

I am not sure you can class this as an issue, but I was wondering if you could give a minimal example of the PON vcf? I keep running into the following error as part of the validate_panel_normal_vcf function:

`ERROR - INFO flag 'PANEL_OF_NORMALS' is missing from the panel of normal VCF header`

I've tried to edit the vcf header to include the string: "PANEL_OF_NORMALS" but to no avail.

Regards,
Ridwan

**Comment by sigven** [comment]
Hi Ridwan,
Thanks for reaching out, working to get a new release out, but difficult times with kids at home all day:-) Regarding the PON VCF, make sure your VCF entries are formatted with the panel-of-normals flag, also including a header:

`##INFO=<ID=PANEL_OF_NORMALS,Number=0,Type=Flag,Description="Panel of normals germline variant">`

All PON entries should have the `PANEL_OF_NORMALS`flag in their INFO column.

Let me know how that works for you.

best,
Sigve

**Comment by ridwan-shaikh** [comment]
Hi Sigve,

This is the time you get to realise just how tough a teachers job is! A new found appreciation of the patience that they have.

Thanks. This now works, although I don't see to see much difference when using the PON vs without using the PON. Although I have only tested one sample so far, maybe by luck this sample does not have many artefacts in the sequencing data.

Thanks again and stay safe.
Ridwan
