### ISSUE TITLE
Updating PCGR Databases and VEP

### ISSUE THREAD

**Issue by Senpumaru** [sigven/pcgr#113]
Hello, first of all I want to Thank for such amazing system to annotate VCF files.

I am running currently VEP 100, for annotation purposes (standalone) with vcf2maf. I wanted to ask if it is possible to update VEP to newest version, with some personal modifications to the code, and update databases, without breaking the workflow. This system looks very applicable in my work and quickly became a fundamental part of many pipelines, therefore I want to update it myself, just in case if there would be some big delays or difficulties with new releases.

P.S. I also appreciate a lot your other annotation systems, like gvanno, great stuff.

With Regards,
Nicholas.

**Comment by sigven** [comment]
Dear Nicholas,

Thanks for getting in touch. I have been delayed the last months with the data update, but hopefully this will get completed within June (VEP 100 and other db's). As you have probably noticed, gvanno is already updated with VEP 100, while pcgr requires more testing before I can release the update. I have also been working on a [dashboard like report output](http://folk.uio.no/sigven/TCGA_TEST_0001.pcgr_acmg.grch37.flexdb.html) that I hope to include in the forthcoming release.

Stay tuned, thanks for your patience:-)

regards,
Sigve

**Comment by Senpumaru** [comment]
Dear Sigve,

Thank You for the reply. The new dashboard design looks amazing, slick. I can say honestly, that I haven't seen as polished, quick and thought through system for annotation and reporting in any programming language. Illumina's Nirvana pales in comparison. I will be looking carefully towards the development of this system.

With Regards,
Nicholas.

**Comment by sigven** [comment]
Check out the new release (0.9.0rc)! :-) Closing this issue for now.

**Comment by Senpumaru** [comment]
Thanks for the update, gonna test it soon on new data. I was very inspired by your system, and in the meantime I decided to write a similar system in Django with Docker implementation, mostly for local needs.

**Comment by sigven** [comment]
Cool! Also noted this system yesterday (by Harvard/Dana-Farber environment):

https://twitter.com/VanAllenLab/status/1308936770566881280
