### ISSUE TITLE
Tumor type source

### ISSUE THREAD

**Issue by brucemoran** [sigven/pcgr#114]
Hi Sigve,

might have missed it, but what is the source for the `--tumor_type` inputs? I.e. what did you use to generate them?

Dashboard looking v. interesting BTW!

Thanks,

Bruce

**Comment by sigven** [comment]
Hi Bruce,

Very good question, and you have not missed it, it is not explicitly defined anywhere. Short version: I want to base the selection on tumor type on the work done through the [OncoTree](http://oncotree.mskcc.org/#/home) resource, and currently this is partly how it works. 

I also cross-link the entries in OncoTree, which is identified with [concept unique identifiers from UMLS](https://ftp.ncbi.nlm.nih.gov/pub/medgen/README.txt) with [DiseaseOntology](https://disease-ontology.org/) identifiers and [Experimental Factor Ontology (EFO)](https://www.ebi.ac.uk/efo/) identifiers. However, there are several weaknesses (imprecise mappings) and amounts of missing data with these ontologies, so I have added a whole lot of custom fixes to make it meaningful for integration with other datasets used in PCGR (CIViC, Open Targets etc). So currently still a bit messy, I am afraid. I have come to realize from the many hours spent on this that Integration of disease ontologies is probably a dedicated project in itself.. -:)

I have uploaded an [archive] on Google Drive (https://drive.google.com/file/d/1efUXng1JRl7UD6FzDFuNDcsoOtej_vhu/view?usp=sharing) related to this (raw data files, parsers etc) so you can have a look at how it works if you like. Still a bit immature for a GitHub project, but hopefully it can end up there. The script that generates the main mapping is coined 'integrate_phenotype_ontologies.R'. The tumor type used in PCGR is termed 'primary_site' in the final output. I cannot guarantee that all folders etc will work seamlessly in a new environment, but hopefully all the data should be there.

Thanks,
Sigve

**Comment by sigven** [comment]
The full list of cancer subtypes pr. primary site can be explored in a file that is uploaded to GitHub, see the FAQ for more info.

best,
Sigve
