### ISSUE TITLE
PCGR errors

### ISSUE THREAD

**Issue by rlaalswjd** [sigven/pcgr#115]

**Comment by rlaalswjd** [comment]
Trying to run PCGR, I've got the error issue as follows:

2020-07-08 16:27:03 - pcgr-validate-input - INFO - STEP 0: Validate input data
Traceback (most recent call last):
  File "/home/.conda/envs/pcgr/bin/pcgr_validate_input.py", line 10, in <module>
    import annoutils
ModuleNotFoundError: No module named 'annoutils'


As understanding this issue as the absence of the python module named 'annoutils', I attempted to download python module, annoutils, but I encountered this message: 

$ python -m pip install annoutils
Collecting annoutils
  ERROR: Could not find a version that satisfies the requirement annoutils (from versions: none)
ERROR: No matching distribution found for annoutils


To solve this issue, I'm thinking re-installing PCGR but I'm curious about what you think of this. 

Best, 
MJ

**Comment by sigven** [comment]
Hi MJ,

Seems very much like you have not been able to install it correctly (I assume you are using the Conda-based solution)?

regards,
Sigve

**Comment by rlaalswjd** [comment]
Dear Sigve

Yes. 
Cause I'm not sure which step has had the mistake, so do you have any idea of something that I should be more cautious of during re-installing it? 

Best, 
MJ

**Comment by pdiakumis** [comment]
Hi @rlaalswjd 
Just to be sure, you followed the conda installation instructions as described in https://github.com/sigven/pcgr/blob/master/install_no_docker/README.md, right? That might help to narrow it down a bit.

**Comment by rlaalswjd** [comment]
Dear @sigven @pdiakumis 

Thank you for your help. 

During condarized PCGR installing, download failures are coming up coming up constantly like this: 
[image](https://user-images.githubusercontent.com/68000763/87021920-bdee5580-c210-11ea-9797-f57722c36399.png)

I tried several times but downloaded files are somewhat seemed broken. 
Otherwise, it fails to download. 

Is this because of the increased download traffic? 

Best, 
MJ

**Comment by pdiakumis** [comment]
Hi @rlaalswjd 
That looks like it can't find that Perl script - did you do `wget https://raw.githubusercontent.com/circulosmeos/gdown.pl/master/gdown.pl` as mentioned in that file I linked to above?

**Comment by rlaalswjd** [comment]
Dear @pdiakumis 


Yes. 
Here are the errors: 

[prissys2@gpu01 pcgr]$ conda activate pcgr
(pcgr) [prissys2@gpu01 pcgr]$ wget https://raw.githubusercontent.com/circulosmeos/gdown.pl/master/gdown.pl
--2020-07-09 20:00:00--  https://raw.githubusercontent.com/circulosmeos/gdown.pl/master/gdown.pl
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.64.133, 151.101.192.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2072 (2.0K) [text/plain]
Saving to: ‘gdown.pl’

gdown.pl                              100%[========================================================================>]   2.02K  --.-KB/s    in 0s

2020-07-09 20:00:01 (17.6 MB/s) - ‘gdown.pl’ saved [2072/2072]

(pcgr) [prissys2@gpu01 pcgr]$ perl gdown.pl "https://drive.google.com/uc?id=1wpVqlgY5jBKkQaTAxzgf0rgxKxOEJgj-" grch38.tar.gz
Cannot open cookies file ‘gdown.cookie.temp’: No such file or directory
--2020-07-09 20:00:28--  https://drive.google.com/uc?id=1wpVqlgY5jBKkQaTAxzgf0rgxKxOEJgj-
Resolving drive.google.com (drive.google.com)... 172.217.26.46, 2404:6800:4004:80d::200e
Connecting to drive.google.com (drive.google.com)|172.217.26.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘grch38.tar.gz’

     0K                                     16.1M=0s

2020-07-09 20:00:29 (16.1 MB/s) - ‘grch38.tar.gz’ saved [3082]

Couldn't download the file :-(


Thanks, 
MJ

**Comment by sigven** [comment]
Hi MJ,
Truly sorry for the inconvenience. The issue with Google Drive has been experienced before, try the host mentioned in this thread:
https://github.com/sigven/pcgr/issues/95#issuecomment-584553139

I will issue a statement in the forthcoming release that this should be the preferred host going forward.

regards,
Sigve

**Comment by rlaalswjd** [comment]
Dear @sigven @pdiakumis 

Thank you for your help. 

In spite of your help, as the errors constantly coming up during condarized installing, 
I changed the plan from conda-based to docker-based installation. 

Yet, I've got same error as follows:

[prissys2@gpu01 docker_run_test]$ docker pull sigven/pcgr:0.8.4
0.8.4: Pulling from sigven/pcgr
Digest: sha256:c65ef37bf34562b64b2c5ce930db4275a3941dfe8bd4a526dfdb5bcf0fc710ec
Status: Image is up to date for sigven/pcgr:0.8.4
docker.io/sigven/pcgr:0.8.4

[prissys2@gpu01 docker_run_test]$ /data/prissys2/mutation_panel/PCGR_tiering/pcgr-0.8.4/pcgr/pcgr.py /data/prissys2/mutation_panel/PCGR_tiering/pcgr-0.8.4/pcgr /data/prissys2/mutation_panel/PCGR_tiering/docker_run_test/ --no_vcf_validate --input_vcf ./testinput_1.vcf grch38 /data/prissys2/mutation_panel/PCGR_tiering/pcgr-0.8.4/pcgr/conf/pcgr.toml testrun
2020-07-14 16:43:55 - pcgr-validate-config - ERROR -
2020-07-14 16:43:55 - pcgr-validate-config - ERROR - Docker image sigven/pcgr:dev does not exist, pull image from Dockerhub (docker pull sigven/pcgr:dev)
2020-07-14 16:43:55 - pcgr-validate-config - ERROR -


And secondly, I'm curious about the pcgr.toml. 
In the previous version of PCGR I used (0.8.1), cancer-specific .toml files (e.g. Colorectal cancer _nos.toml) were provided in configuration directory. It seems only the united .toml (pcgr.toml) is provided in the latest version. Am I right? or am I missing sth? If I am right, is there no problem in the way of using the combined version of pcgr.toml in case of purpose for cancer-specific analyses? 


Thanks. 

Best regards,
MJ

**Comment by rlaalswjd** [comment]
Dear @sigven @pdiakumis 

Thank you for your help. 

In spite of your help, as the errors constantly coming up during condarized installing, 
I changed the plan from conda-based to docker-based installation. 

Yet, I've got same error as follows:

[prissys2@gpu01 docker_run_test]$ docker pull sigven/pcgr:0.8.4
0.8.4: Pulling from sigven/pcgr
Digest: sha256:c65ef37bf34562b64b2c5ce930db4275a3941dfe8bd4a526dfdb5bcf0fc710ec
Status: Image is up to date for sigven/pcgr:0.8.4
docker.io/sigven/pcgr:0.8.4

[prissys2@gpu01 docker_run_test]$ /data/prissys2/mutation_panel/PCGR_tiering/pcgr-0.8.4/pcgr/pcgr.py /data/prissys2/mutation_panel/PCGR_tiering/pcgr-0.8.4/pcgr /data/prissys2/mutation_panel/PCGR_tiering/docker_run_test/ --no_vcf_validate --input_vcf ./testinput_1.vcf grch38 /data/prissys2/mutation_panel/PCGR_tiering/pcgr-0.8.4/pcgr/conf/pcgr.toml testrun
2020-07-14 16:43:55 - pcgr-validate-config - ERROR -
2020-07-14 16:43:55 - pcgr-validate-config - ERROR - Docker image sigven/pcgr:dev does not exist, pull image from Dockerhub (docker pull sigven/pcgr:dev)
2020-07-14 16:43:55 - pcgr-validate-config - ERROR -


And secondly, I'm curious about the pcgr.toml. 
In the previous version of PCGR I used (0.8.1), cancer-specific .toml files (e.g. Colorectal cancer _nos.toml) were provided in configuration directory. It seems only the united .toml (pcgr.toml) is provided in the latest version. Am I right? or am I missing sth? If I am right, is there no problem in the way of using the combined version of pcgr.toml in case of purpose for cancer-specific analyses? 


Thanks. 

Best regards,
MJ

**Comment by sigven** [comment]
Hi, 

Make sure you download the 0.8.4 release, and run the pcgr.py present there. Seems you are mixing files from the dev version with the 0.8.4 (most stable). Use the pcgr.toml file in the 0.8.4 version, specify tumor type as argument.

Best, 
Sigve

**Comment by sigven** [comment]
Closing this for now, check the new release (0.9.0rc).
