### ISSUE TITLE
AD/AF not displaying for tumor only mode

### ISSUE THREAD

**Issue by Shruti-Desai** [sigven/pcgr#119]
Hi Sigve,
I am annotating vcf (##fileformat=VCFv4.2) called from GATK4 using pcgr. But when the html is generated tumor depth and frequency information is till coming blank. Tried adding AC/AF/DF from the vcf in config toml, but it gives error saying these fields are reserved for the vcf INFO column.
I am running pcgr (0.8.4 - using earlier versions since I am validating the samples I had ran earlier, with compatible docker image-sigven/pcgr:0.8.4 and data bundle pcgr.databundle.grch38.20191116.tgz) on Mac Sierra.
Thanks ,
Shruti

**Comment by sigven** [comment]
Hi Shruti,
Could you provide your config and VCF file, in order to figure out what is not working?

regards,
Sigve

**Comment by Shruti-Desai** [comment]
Hi Sigve,
Sent you files on your mail id.

**Comment by Shruti-Desai** [comment]
> Hi Sigve,
> Sent you files on your mail id.

**Comment by sigven** [comment]
Thanks, I'll have a look next week (not at work presently).

kind regards,
Sigve

**Comment by sigven** [comment]
Hi Shruti,

Sorry for my late response. Had a look at your input file, and I can try to explain your error:

- To specify tumor depth/allelic fraction, you must add your own custom VCF tags to the INFO column. PCGR does not want to interfer with  [reserved VCF info tags](https://samtools.github.io/hts-specs/VCFv4.2.pdf), so try to simply add a dedicated tag, e.g. `TDP=20;` (tumor depth), with a value denoting the tumor sequencing depth for the alternate allele. If you look at the example VCF files in the PCGR repo, you get a feel for how it should be formatted.

- As a second note, are you sure the calling procedure with GATK4 is intended for somatic variant detection? From the AF values, it seems it is geared towards germline variants (AF being mostly 0.5 and 1, which is the case for germline variants)

Closing the issue for now.

Thanks,
Sigve

PS. Try using the latest release whenever possible, as bugs are fixed and general improvements are made.
