### ISSUE TITLE
Error in overscope_eval_next(overscope, expr) 

### ISSUE THREAD

**Issue by choosehappy** [sigven/pcgr#12]
hello,

i just install PCGR and tried it with a vcf file i had laying around and this error was generated:

```
2017-11-28 22:09:37 [INFO] Number of block substitutions: 0
2017-11-28 22:09:37 [INFO] Determination of deletion mechanisms (repeat, microhomology etc) by investigation of junction sequence
2017-11-28 22:09:37 [INFO] Extending annotation descriptions related to PFAM protein domains
2017-11-28 22:09:38 [INFO] Extending annotation descriptions related to UniprotKB/SwissProt protein features
2017-11-28 22:09:41 [INFO] Extending annotation descriptions related to Database of Curated Mutations (DoCM)
2017-11-28 22:09:42 [INFO] Extending annotation descriptions related to ClinVar
2017-11-28 22:09:44 [INFO] ------
2017-11-28 22:09:44 [INFO] Generating data for tiered cancer genome report - somatic calls
2017-11-28 22:09:44 [INFO] Predicting microsatellite instability status
Error in overscope_eval_next(overscope, expr) :
  object 'CALL_CONFIDENCE' not found
Calls: <Anonymous> ... map -> lapply -> FUN -> overscope_eval_next -> .Call
Execution halted
```

any idea what the issue is?

**Comment by choosehappy** [comment]
actually it might relevant to these warning from further up:

```
2017-11-28 21:41:09 - pcgr-validate-input - INFO - Checking if existing INFO tags of query VCF file coincide with PCGR INFO tags
2017-11-28 21:41:09 - pcgr-validate-input - INFO - No query VCF INFO tags coincide with PCGR INFO tags
2017-11-28 21:41:09 - pcgr-validate-input - WARNING - Could not find the specified --call_conf_tag (TAL) in INFO column of input VCF
2017-11-28 21:41:09 - pcgr-validate-input - WARNING - Could not find the specified --tumor_dp_tag (TDP) in INFO column of input VCF
2017-11-28 21:41:09 - pcgr-validate-input - WARNING - Could not find the specified --tumor_af_tag (TVAF) in INFO column of input VCF
2017-11-28 22:41:17 - pcgr-validate-input - INFO - Finished
```

but to be honest, i'm not sure where those columns come from? 

i'm using a vcf file generated by mutect

**Comment by choosehappy** [comment]
i also have snps called from varscan for a different patient, and those vcfs don't have any of those columns either.

by the way, i'm only providing a vcf and not a copy number segment file at this time

**Comment by choosehappy** [comment]
so i think i've already made some progress.

first off, it helps to isolate just the tumor sample from the normal sample (my vcf file contained a column for normal and a column for tumor), i did this using bcftools like so:

bcftools view -c1 -Oz -s EGAN00001186195 -o EGAN00001186195.vcf.gz PD18791_pri.mutect.recal.variants.vcf.gz


then, one has to edit the pcgr_configuration.toml file to align with the columns in the respctive VCF file. this is what i'm at now but am still at a loss...

my VCF contains this:

```
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=FA,Number=A,Type=Float,Description="Allele fraction of the alternate allele with regard to reference">
....
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  EGAN00001186195
1       10257   .       A       C       .       REJECT  AC=1;AN=2       GT:AD:BQ:DP:FA  0/1:1,2:30:3:0.667
1       10292   .       A       T       .       REJECT  AC=1;AN=2       GT:AD:BQ:DP:FA  0/1:1,1:32:2:0.5
1       10321   .       C       T       .       REJECT  AC=1;AN=2       GT:AD:BQ:DP:FA  0/1:0,1:28:1:1
1       10390   .       C       A       .       REJECT  AC=1;AN=2       GT:AD:BQ:DP:FA  0/1:4,2:30:7:0.333

```

so as such in the toml file i set (note, there is no conf provided by mutect or varscan):

```
[allelic_support]
tumor_dp_tag = "DP"
tumor_af_tag = "FA"

```

but i still get this warning:

```
2017-11-28 22:33:28 - pcgr-validate-input - WARNING - Could not find the specified --tumor_dp_tag (DP) in INFO column of input VCF
2017-11-28 22:33:28 - pcgr-validate-input - WARNING - Could not find the specified --tumor_af_tag (FA) in INFO column of input VCF
2017-11-28 22:33:28 - pcgr-validate-input - WARNING - Could not find the specified --call_conf_tag (TAL) in INFO column of input VCF

```


any ideas?

**Comment by sigven** [comment]
Hi, 
Thanks for reporting this. We specifically request that any tag relating to the depth/allelic fraction should be specified in the VCF INFO column (this since it's not trivial to fetch this correctly within the FORMAT/SAMPLE columns for the multitude of somatic callers that format this in their very own way, often not complying with any standards). This is causing the last warnings. We are aware that others would also like to have this fetched from the SAMPLE columns, but since PCGR is intended for single cases/samples, we believe it won't harm the VCF content to place sample-specific information in the INFO column. That being said, your initial error (CALL_CONFIDENCE) was a bug that I am resolving in the next release (0.5.3 tomorrow), so hopefully things should run better when that is fixed.  I'll keep you posted.

regards,
Sigve

**Comment by ohofmann** [comment]
Sigve, we are looking into this as well right now (cc @vladsaveliev ). Are you aware of any annotation tool that would allow injection of AF / DP information into the INFO column? It's a feature request for vcfanno (https://github.com/brentp/vcfanno/issues/15) but not implemented yet.

**Comment by choosehappy** [comment]
thanks

i wrote some code for another project (Mupexi) that you can use to extract allele frequency from the genotype columns. 

its been tested with mutect/varscan/freebayes/vardict and the ensemble calls produced by bcbio:

https://gist.github.com/choosehappy/e54f23e41ad9246bdafd4d4ceb4e97d7

is it worth integrating?

**Comment by sigven** [comment]
Hi Oliver and @choosehappy,
Wrt your comment Oliver: I am really not sure about any such general tool that perform such an operation. This is generally somewhat complicated since it is not trivial to know what refers to the tumor/control sample (we have seen a version of MuTect that is not deterministic in the placement of tumor/control column), and how the allelic support is defined. In many instances, an 'AD' tag is given, which indicates read support (often consisting of quality-filtered reads) for the ref and alt allele. When other alleles (that is not ref or alt) also present, the allelic fraction cannot be computed solely based on the AD information, the DP should really be used for computing the allelic fraction of the alt allele. The gist provided by @choosehappy could be a good start for handling the matter internally within PCGR, since you are clearly covering most common somatic callers. I will definitely look into this. As already hinted to, however, there are a bunch of ways that callers report on this (I believe for instance Strelka has their very own way). Ideally, one should make an intitiative that puts forward a standard for this that would simplify the downstream processing, making things less error-prone, but I am not sure how to go about that. I am either way open for suggestions!

**Comment by choosehappy** [comment]
I certainly appreciate that the column ordering can be a pain; I witnessed a similar nightmare a few weeks ago. 

I don't think, for simplicity sake, its too burdensome to expect users to either run the bcftools command i mentioned above, which extracts a single sample from a multi-sample vcf file or to explicitly request the sample name at run time and then wrap the same command internally inside of PCGR. this way, downstream, there will be only a single column present 


as for a standard... unlikely to change in the near future i'm afraid. there are simply too many legacy tools floating around with large code bases built upon them that no one would dare update them to a standard, even if there was one. i think the only real hope on that front is that in the future a "master of all" variant caller will be created, which will be a superset of all the features of all the other callers, and their format will become the de facto standard going forward

**Comment by sigven** [comment]
Yeah, I have been thinking along the same lines, that I could request the sample names at run time. I think that's the easiest way to go. I think having this as a second line of processing (if data is not present in the INFO column already) might be useful, and could cater for most cases. I guess you are right with the standards not going to change.. guess it's my frustration of the matter. @choosehappy:  would you be able to share a folder with example VCF's from the most common callers? Also indicating software verions?

Sigve

**Comment by choosehappy** [comment]
sure, these just finished running today:

https://www.dropbox.com/sh/z3ev07ocv4fglie/AABAYl9BaLqnV_Hs6c_pyCbQa?dl=0

these were produced using the bcbio pipeline (https://github.com/chapmanb/bcbio-nextgen)

there is: freebayes, mutect, vardict, varscan and "ensemble", where at least 2 callers were in agreement on the call. they're all annotated by various databases (thus the atypical "INFO" fields, but i think you're not interested in those in this case). version numbers, command line params, etc are in the headers

**Comment by sigven** [comment]
Great, thanks for contributing so nicely. I am closing the issue for now, implying that I am to go forward with an integration of this.

regards,
Sigve

**Comment by choosehappy** [comment]
one quick thing which tripped me up (and spawned the writing of the gist above). 

the "ensemble" vcf takes the row from whichever variant caller produced the variant "first". so if you look closely, you'll see that the genotyping column fields may be entirely different per line. thus that file formatting is actually a combination of all 4 formattings of the other callers. fun fun!

**Comment by sigven** [comment]
thanks for the notice.. far from fun !:-)

**Comment by ohofmann** [comment]
This may be counterproductive but can I advise against trying to handle this within PCGR? You'd be on the hook for maintaining support for a large variety of callers / VCF flavours being used; I really feel this is something we ought to address upstream (e.g., working with Brent on vcfanno, then postprocessing samples as needed).

**Comment by sigven** [comment]
I appreciate this advice, and that has really been my point as well, that this should be handled upstream. It would be quite a huge job, and likely introducing a complex code base that needs continues updates. It seems though that there are a number of users that lacks the necessary competence on the upstream handling /VCF input, so for them it would of course be a huge asset.

**Comment by choosehappy** [comment]
To be fair, to me knowledge the formats used by the popular callers (e.g., varscan, mutect, etc) aren't changing, so supporting these legacy callers seems like a one-off investment to me. Adding new callers would of course require additional maintenance, but hopefully they'd homogenize around a pre-existing format. 

Maybe looking at what other projects are doing is useful and/or have components/code which can be integrated directly to address the problem? I haven't seen any other tools which require this type of data in the INFO field, so they must have some solution? potentially it could be as simple as wrapping around vcftools which is mature, and asking the user which fields should be considered?

**Comment by sigven** [comment]
If you can find any such tools, please share them with me. Another concern is how well they handle multiallelic sites.

**Comment by choosehappy** [comment]
All of the tools i've seen use the PyVCF to load the VCF file (https://pyvcf.readthedocs.io/en/latest/). from there pulling individual columns/samples is trivial. The code from my gist is actually based on using this package. Not sure anything else is needed if the user is required to explicitly state the name of the specimen (or defaults to the sample in the "0"th column) and the associated columns they would like to use (as you have now for the info field). In that case, no per variant caller code is necessary as the user manually provides the relationship between their columns and your target information.

Anyway, I thought about this a bit more, and I also don't think its unreasonable to expect users to use a 3rd party tool to put their VCFs into an appropriate format (e.g., single sample with info in the INFO column) if thats what is required. again i imagine any such tool would still require specimen name, and a list of the the desired fields, like above

As @ohofmann mentioned, I'm unaware of any tool currently which does this though, which is making me wonder more how you created your own VCFs? That is to say, I've yet to successfully run PCGR on one of my samples, so if you have a secret command/tools which reformats VCFs to your spec, i would be very interested in using it :)

**Comment by sigven** [comment]
The VCF's in PCGR's example folder are in fact customly-made VCF's by combining data from multiple MAF files released by TCGA (muse, mutect2, varscan2, somaticsniper). 

Either way, just for the fun of it, and for @choosehappy to look further into, I made an initial attempt to pull down depth and allelic fraction of the tumor and control for freebayes and mutect using the example VCF files that were shared. The resulting code can be found here (a lot of duplicated code and missing exception handling, but it illustrates how it can be implemented), lending highly upon [cyvcf2](https://github.com/brentp/cyvcf2):

https://gist.github.com/sigven/1343995dd18b857ae71bf2963138b11c

I have no idea how this should pan out for multiallelic sites (i.e. VCF's that has not been decomposed)

PS1 @choosehappy : the VCF files you shared with me are hg38, not currently supported by PCGR
PS2 @choosehappy : it seems many of the VCF files are not formatted correctly (does not pass [EBI's VCF-validator](https://github.com/EBIvariation/vcf-validator). The AD tag appears to be wrongly formatted. This further demonstrates how challenging this excercise can be (to have as an internal PCGR part, that is)

**Comment by choosehappy** [comment]
sorry for the delay, i took your code and modified it to what i think will support all variant callers, and is easily extensible to any future formats:

https://gist.github.com/choosehappy/d2eba4bfc7fb01b755eb8ecccc55b597

i've used it and the reports come out as expected, thanks for your hard work!
