### ISSUE TITLE
Download of data bundle

### ISSUE THREAD

**Issue by V-Catherine** [sigven/pcgr#120]
I get an error message when trying to download the data bundle:
wget http://insilico.hpc.uio.no/pcgr/pcgr.databundle.20201123.grch37.tar.gz -O grch37.tar.gz
--2020-12-29 15:49:17--  http://insilico.hpc.uio.no/pcgr/pcgr.databundle.20201123.grch37.tar.gz
Resolving insilico.hpc.uio.no (insilico.hpc.uio.no)... 129.240.189.148
Connecting to insilico.hpc.uio.no (insilico.hpc.uio.no)|129.240.189.148|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-29 15:49:18 ERROR 404: Not Found.

**Comment by sigven** [comment]
Hey, try to replace `tar.gz`with `tgz`, I think that is the reason your download does not work.

kind regards,
Sigve
