### ISSUE TITLE
"PCGR data bundle is not compliant with the software version"

### ISSUE THREAD

**Issue by V-Catherine** [sigven/pcgr#121]
Hi,
I've installed pcgr without docker (using conda) and when I run it with your test data, I get the following error:
"pcgr-validate-arguments-input - ERROR - The PCGR data bundle is not compliant with the software version - please download the latest software and data bundle (see https://github.com/sigven/pcgr for instructions)"
I downloaded the 20201123 data bundles with the links you provided. 
Do you think you could help solving this issue ?
Thanks in advance,
Catherine

**Comment by sigven** [comment]
Hi Catherine,

Which version is shown when you type `pcgr.py --version` in your terminal? And you are sure that `which pcgr.py`points to the script in your pcgr Conda environment? If this is so, at the top of the `pcgr.py` script there should be a line indicating the correct version of the data bundle, i.e. :

`DB_VERSION = 'PCGR_DB_VERSION = 20201123'`

If you see a different DB_VERSION in your script, you are using an old Conda-based installation, and should revisit the installation to make sure you have the latest.

regards,
Sigve

**Comment by V-Catherine** [comment]
Hi Sigve,
Thanks for your answer. `pcgr.py --version` gives: 0.9.1. `which pcgr.py` points indeed to the script in my pcgr conda environment and at the top of the script I have: 
PCGR_VERSION = '0.9.1'
DB_VERSION = 'PCGR_DB_VERSION = 20201123'
Best regards,
Catherine

**Comment by sigven** [comment]
Hi Catherine,

If you still encounter the same error I am unsure what is going wrong, it should work if you have downloaded the 20201123 bundle and provide the correct data directory when calling PCGR.

kind regards,
Sigve

**Comment by V-Catherine** [comment]
Thanks for suggesting a data directory issue. The path to the data dir was actually one level above what it should be. Now it works. Sorry it was my mistake. Thanks again for you help :-)

**Comment by sigven** [comment]
Great! Closing issue.
