### ISSUE TITLE
Data bundle unavailable to download

### ISSUE THREAD

**Issue by ridwan-shaikh** [sigven/pcgr#123]
Hi Sigve,

I am having problems downloading the latest data bundle. It appears that the site can’t be reached.

Regards,
Ridwan

**Comment by sigven** [comment]
Hi Ridwan,

Thanks for the notification. Tried myself now, same error. I’ll check with the system administrators to see what’s going on.

Regards, 
Sigve

**Comment by sigven** [comment]
Hi again,

Server is still down. Meanwhile, try access the same bundles from Google Drive:

[grch38](https://drive.google.com/file/d/1iLe_ux4Y7sbkdBDTZKnOlsMmouMtDNrw/view?usp=sharing)
[grch37](https://drive.google.com/file/d/1Fp4pYp4rU8Q0IFsKIRPV5pbhpT17rs0l/view?usp=sharing)

Sorry for the inconvenience.

regards,
Sigve

**Comment by ridwan-shaikh** [comment]
Perfect! Thanks Sigve!
