### ISSUE TITLE
Eitems counting bug - var_eitems by type

### ISSUE THREAD

**Issue by 1seokyoo** [sigven/pcgr#126]
Hi sigven,

Using PCGR to append CGI, CIViC evidence information, An error occurred.
The error message is as follows.
>_Error in matrix(value, nrow = nr, dimnames = list(rn, cn)) :
>   data is too long
> Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> NROW -> Ops.data.frame -> matrix
> Execution halted_

When I checked the code where the error occurred, I found that the code that calculates var_eitems by type is wrong.
If you check line 713 of pcgrr/R/biomarkers.R, the code is written as "_**NROW(var_eitems[[m]]]> 0)) {**_".
It has been confirmed that the above error occurs in "**_var_eitems[[m]]> 0_**".
So I modified it with "**_NROW(var_eitems[[m]])> 0) {_**" and it worked without any problems.
Please check the error code.

Thanks,
Wonseok

**Comment by sigven** [comment]
Hi Wonseok,

Thanks a lot for reporting, indeed a bug. Will be fixed in next release.

regards,
Sigve

**Comment by sigven** [comment]
Fixed in v0.9.2
