### ISSUE TITLE
Failed to install pcgr in R

### ISSUE THREAD

**Issue by Wangxin555** [sigven/pcgr#127]
Hi,

I downloaded the tar.gz to install this package in R, but I continue getting this:
```
ERROR: dependency 'rlogging' is not available for package 'pcgrr'
* removing 'D:/Software/R-4.0.3/library/pcgrr'
Warning in install.packages :
installation of package ‘D:/pcgrr_0.9.1.tar.gz’ had non-zero exit status
```
Also, I failed to find rlogging package in CRAN or Bioconductor. Any suggestion?

Sessioninfo:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
```

**Comment by sigven** [comment]
Hi,

If I understand you correctly, you are trying to install the `pcgrr` R package only. Note that the `pcgrr` R package as part of the pcgr pipeline is not currently a standalone package, but rather relies upon input from the initial parts of the pcgr pipeline. For the `rlogging` package, check [this link](https://github.com/mjkallen/rlogging#installation). 

regards,
Sigve
