### ISSUE TITLE
Could pcgr run with singularity

### ISSUE THREAD

**Issue by YingYa** [sigven/pcgr#128]
Hi sigven，

Could pcgr run with singularity？

**Comment by sigven** [comment]
Hi @YingYa,

Yes, you can install PCGR inside a singularity container (for example through Conda, following the [outlined instructions](https://github.com/sigven/pcgr/tree/master/install_no_docker)) and use the container to analyse data with PCGR. We have done this successfully locally at our institution.

regards,
Sigve
