### ISSUE TITLE
tumor ploidy and tumor purity not showing in the report when provided as parameters

### ISSUE THREAD

**Issue by tinavisnovska** [sigven/pcgr#129]
Hello, 

in pcgr v0.9.1, when I provide --tumor_ploidy and --tumor_purity parameters, the report comes up saying that the values were not provided/determined. 

it seems to me that the values are not updated when the report is generated - neither in generate_pcgr_report() (main.R) nor in init_report() (report.R) after the default value "Not provided/determined" is set.

Cheers, 
Tina

**Comment by sigven** [comment]
Fixed in v0.9.2
