### ISSUE TITLE
It can't be extracted EXON and INRON information from vcf INFO tag annotated by the vep with --preserved_info_tags EXON,INTRON parameters?

### ISSUE THREAD

**Issue by QifengSun** [sigven/pcgr#135]
Hi @sigven,

![image](https://user-images.githubusercontent.com/18737212/127245070-574fa0a8-9217-4b89-99d6-b871854a3e2a.png)

the **INFO** tags ### EXON and the **INTRON** was generated by the **VEP --numbers** parameter  NOT in the _original input vcf file_ but in the middle file ***.pass.vcf.gz**. So it doesn't work use the **--preserved_info_tags EXON,INTRON**. 

The INFO tags EXON,INTRON show the EXON position the variance occurs out of the total EXONs, like "7/10" . So it it very convenient. 

 I hope the next version could 
1. add the **--custom_tags** parameters for the user, it it very convenient to customized the local analysis work flow especially for the outcomming of the VEP annotation INFO tags.
2. add the **--vep_option** parameters to customized the VEP annotation procedure.
3. add the **vep --custom** parameter to support the vep local database annotation.
4. leave the script outside the docker and use -v to mapping the the script direcory, make the user easy to mantain the script.

regards,
Qifeng

_Originally posted by @QifengSun in https://github.com/sigven/pcgr/issues/134#issuecomment-887929277_

**Comment by sigven** [comment]
hi @QifengSun,

The INFO tags **EXON** and **INTRON** are already appended by the VEP processing in PCGR, and will be present in the output file `<sample_id>.pcgr_acmg.<genome_assembly>.pass.tsv.gz` (basically a tab-separated version of the PCGR-annotated query VCF). The columns are presently not included in  output file focusing on the tiers, i.e. `<sample_id>.pcgr_acmg.<genome_assembly>.snvs_indels.tiers.tsv`, but I can gladly add them to this output file as well. So you should not need to add these to the `--preserved_info_tags` argument (only tags present in your query VCF should be listed here).

Some additional comments regarding your wishes for VEP customization in the next release:

Regarding point **1.**, what does the `--custom_tags` option refer to? In PCGR, you can keep whatever INFO tags you like from your query VCF in the PCGR-annotated output, using the option `--preserved_info_tags`. If you want to add custom annotation tracks to your VCF, please do this outside of PCGR (i.e. prior to PCGR execution). Importantly, serving users with the possibility to annotate their VCF with other datasets is beyond the scope of the tool (many other tools can do this), and this part should thus be done prior/upstream of PCGR analysis (relates also to your point **2.** I believe). 

Regarding point **3.**, please note that PCGR relies upon a number of parameters in the VEP annotation procedure, so making it possible for users to customize this part will imply a substantial amount of work/code, and where the added flexibility is minimal, so I really do not think this is a good idea. Most annotations provided by VEP is already present in the output (`pass.tsv.gz` files), if you want to exclude particular parts, I suggest you add a post-processing script to your workflow.

kind regards,
Sigve
