### ISSUE TITLE
control_dp_min is not properly transfered

### ISSUE THREAD

**Issue by gudeqing** [sigven/pcgr#136]
![image](https://user-images.githubusercontent.com/30919159/133193320-161ccfa0-5d4a-4fd1-9214-7b24b01286f3.png)

**Comment by sigven** [comment]
Hi @gudeqing,
Thanks a lot for noticing this! Indeed a bug, pushed a fix to `pcgr.py` now.

best,
Sigve

**Comment by gudeqing** [comment]
Hi @sigve，
will you check if the following arguments work as expected ？
--tumor_dp_min 5 \
--tumor_af_min 0.05 \
--tumor_dp_tag TDP \
--tumor_af_tag TAF \
--control_dp_tag NDP \
--control_af_tag NAF

best wishes ！

**Comment by sigven** [comment]
Sure thing, if you have an example VCF that you think adheres to these parameters, I could do such a check. I would also need the assembly version (grch37 or 38)

**Comment by gudeqing** [comment]
Hi, sigven,
  Nice to have it work properly now.  
By the way, here is a small script that helps to copy "DP/AF" in FORMAT  to INFO field, However, I  still hope by default, pcgr will extract info from FORMAT, and I believe this will cover 90% real cases of somatic variant calling.

```python
from pysam import VariantFile


def reformat_vcf(vcf_file, out):
    with VariantFile(vcf_file) as fr:
        header = fr.header
        header.info.add('TDP', number=1, type='Integer', description='Tumor sample depth')
        header.info.add('NDP', number=1, type='Integer', description='Normal sample depth')
        header.info.add('TAF', number=1, type='Float', description='Tumor sample AF')
        header.info.add('NAF', number=1, type='Float', description='Normal sample AF')

        with VariantFile(out, 'w', header=header) as fw:
            for record in fr:
                record.info['TDP'] = record.samples[1]['DP']
                record.info['NDP'] = record.samples[0]['DP']
                record.info['TAF'] = record.samples[1]['AF'][0]
                record.info['NAF'] = record.samples[0]['AF'][0]
                fw.write(record)

```

**Comment by sigven** [comment]
Hi @gudeqing,

Cool! Very nice small script for this purpose. Although I agree that retrieving this information directly from the FORMAT column would by far be most convenient for most people, the fact that there is no concensus (among callers) on how to format sample-specific variant data in the FORMAT column makes it inevitably fairly challenging to parse this information robustly. This has at least been my experience over the years, I have seen callers with poor consistency in their way of formatting. E.g. how can one be sure that `record.samples[1]` denotes the tumor sample? And how do you ensure that the `record.samples[1]['AF'][0]` is a single value and not a comma-delimited value (for multiallelic calls)? So IMO there are some potential pitfalls here, but if you can demonstrate that a robust parsing scheme for this across the most common somatic callers, I am happy to have a look at it for integration into PCGR :-)

**Comment by sigven** [comment]
Hi @gudeqing, I will follow up now on the great contribution you have done here. I am in the process of updating PCGR, and will be looking into how your work could be incorporated, either fully, or as a utility that can be offered to the users.
