### ISSUE TITLE
Add a new biomaker (Amino Acid)

### ISSUE THREAD

**Issue by 1seokyoo** [sigven/pcgr#138]
Hi sigven,

I think that a new value called **Amino Acid** should be added in addition to the existing BIOMARKER_MAPPING used in PCGR.

When I actually used PCGR to compare the variant and evidence attached to this, there were cases where the evidence could not be provided when there was the same protein change.

The variant is chr17-37880981-A-AGCATACGTGATG, and the predicted protein change is **ERBB2 p.Y772_A775dup**.

In the case of ERBB2 p.Y772_A775dup, since it is a hotspot variant in Lung cancer, we checked the CIViC DB.

There was a basis for ERBB2 p.Y772_A775dup in the CIViC DB, but the genomic coordinate of CIViC DB was different from my variant.
(CIViC DB: chr17-37880995-A-ATACGTGATGGCT / [Link](https://civicdb.org/events/genes/20/summary/variants/414/summary#variant))

It's not a left-align or right-align issue, the two variants are just different in their genomic coordinates. However, it shows the same protein change.

Therefore, even in the case of a variant in which the same protein change is predicted as the evidence (BIOMARKER_MAPPING is exact), the code was modified and used to attach the relevant evidence.

When I checked, Illumina's Variant Interpreter uses 5 steps of BIOMARKER_MAPPING.
(Nucleotide, Amino Acid, Codon, Exon, Gene)

I think that the case of **Amino Acid (same protein change)** should also be considered in PCGR, so I am writing this.

thanks for reading
Wonseok.

**Comment by sigven** [comment]
Hi @1seokyoo,

Thanks a lot for this input, this is in fact a very good point. Currently, I have a dedicated script that takes the information provided by CIViC, and attempts to map the variants that are listed without any genomic information (i.e. only the amino acid variant, a large number of variants in CIViC is of this nature) towards potential genomic variants, using [TransVar](https://bioinformatics.mdanderson.org/transvar/). The assumption here is that any genomic variant that leads to a particular amino acid variant is equally "valid" for the biomarker listed, an assumption I think is reasonable in most cases, and is really providing support for the case you outline above. However, TransVar is not perfect, and for complex insertions and deletions, it is not able to retrieve all putative variants that lead to a particular amino acid change.

Henceforth, I think your suggested approach, simply adding a step with mapping any CIViC variant by amino acid (i.e. for those not already matched by nucleotide), makes great sense, I will move forward with this, and have this in place for the next update.

Thanks again for your input!

best,
Sigve

**Comment by sigven** [comment]
Quick question: is the variant details you list above (genomic position) for GRCh37?

**Comment by 1seokyoo** [comment]
Yes, **the both variants**(my list and CIViC DB) are above for GRCh37.

Sorry, I entered the variant information(genomic position) in the CIViC DB incorrectly. Variant information are shared again.
(CIViC DB: chr17-37880984-A-ATACGTGATGGCT / [Link](https://civicdb.org/events/genes/20/summary/variants/414/summary#variant))
(NOT, chr17-37880995-A-ATACGTGATGGCT)

Plus add to the variants details. As confirmed below, it can be confirmed that the transcript change of the variants is different, but the protein change is the same.
  1. my list (chr17-37880981-A-AGCATACGTGATG)
      - HGVS.c: NM_004448.3:c.2313_2324dup
      - HGVS.p: **NP_004439.2:p.(Y772_A775dup)**
  2. CIViC DB (chr17-37880984-A-ATACGTGATGGCT)
      - HGVS.c: NM_004448.3:c.2314_2325dup
      - HGVS.p: **NP_004439.2:p.(Y772_A775dup)**


Thank you for quick response.
Wonseok

**Comment by sigven** [comment]
hi @1seokyoo,

There is a dev version (Conda-based) that you can test out now, where I have tried to improve the biomarker mapping (i.e. also catching variants that map at the amino acid level). Installation instructions here:

https://sigven.github.io/pcgr/articles/installation.html

Let me know if the new version works better.

thanks
Sigve
