### ISSUE TITLE
Update R package structure

### ISSUE THREAD

**Issue by pdiakumis** [sigven/pcgr#139]
In an effort to make PCGR a bit easier to maintain, update and test, I've started playing a bit with the R parts and think the pcgrr package setup can be improved with a few simple updates.

My strategy basically involves running the `src/R/pcgrr` R package through `devtools::check()` and systematically tackling the notes/warnings/errors. I'll split up these changes in separate PRs for slightly easier eyeballing, but currently I've got the following general changes somewhat done:

- move raw data generation script to `data-raw/` as generally recommended by the R community
- add/update LICENSE files and DESCRIPTION
- `@export` all functions and allow NAMESPACE to be automatically updated by roxygen2
- update tidyverse functions to use the `foo(.data$VAR, ...)` syntax in place of `foo(VAR, ...)`
- prepare conda recipe for the R package alone
- decouple the 'heavy' BSgenome packages from the package requirements and instead move to the 'Suggests' field of DESCRIPTION

I'll be adding these changes to the `dev` branch so that we can also test without worrying about breaking stuff in `master`. In general I don't expect major functionality changes in PCGR itself, but maybe a variable here or there gets caught out somewhere leading to an error.

I'm keeping this issue here as the main point of communication.

**Comment by sigven** [comment]
Excellent, Peter! All for this.
