### ISSUE TITLE
ERROR:examples

### ISSUE THREAD

**Issue by summer-yangqin** [sigven/pcgr#14]
Hi,
Thanks for providing this tool and source code. 
I had installed the tools in ubuntu.But the example could not run. the error is:

python pcgr.py --input_vcf ~/pcgr-0.5.3/examples/tumor_sample.COAD.vcf.gz --input_cna ~/pcgr-0.5.3/examples/tumor_sample.COAD.cna.tsv  ~/pcgr-0.5.3 ~/pcgr-0.5.3/examples ~/pcgr-0.5.3/examples/pcgr_configuration_examples.toml tumor_sample.COAD --force_overwrite
2018-01-02 16:41:52 - pcgr-check-files - ERROR - 
2018-01-02 16:41:52 - pcgr-check-files - ERROR - Docker image sigven/pcgr:0.5.3 does not exist, pull image from Dockerhub (docker pull sigven/pcgr:0.5.3)
2018-01-02 16:41:52 - pcgr-check-files - ERROR - 

And the docker is running.
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
sigven/pcgr         0.5.3               603420346bcf        4 weeks ago         4.207 GB
<none>              <none>              bef02f2f6467        3 months ago        1.84 kB

So where is my problem. Thanks.

**Comment by sigven** [comment]
Hi, 

That was strange: Is there any output when you type the following on the commandline:
docker images -q sigven/pcgr:0.5.3

Sigve

**Comment by summer-yangqin** [comment]
there is no output when docker images -q sigven/pcgr:0.5.3

But  docker pull sigven/pcgr:0.5.3
~~~~~~
1540c3db5d62: Already exists 
197a2ec5a1f3: Already exists 
603420346bcf: Already exists 
Digest: sha256:2457daf252e075285461e0009a466380f45219a09fb41d35496dbc40aa149bcb
Status: Image is up to date for sigven/pcgr:0.5.3

Thanks

**Comment by sigven** [comment]
Can you please figure out which docker version you are using (`docker -v`)?

Thanks,
Sigve

**Comment by summer-yangqin** [comment]
Docker version 1.6.2, build 7c8fca2

**Comment by sigven** [comment]
OK, that may be the problem. Would you mind upgrading docker, and see if that helps? `docker images -q sigven/pcgr:0.5.3` should list the actual image id (apparently it fails using your docker version). Alternatively, I can make a new pcgr.py script for you that skips the docker image check.
