### ISSUE TITLE
Error: Column `intogen_drivers` not found in `.data`

### ISSUE THREAD

**Issue by YingYa** [sigven/pcgr#169]
Whenever you encounter an error, please also include:

- [0.10.7] Version of PCGR.
- [grch38] Genome build (grch37/grch38).
- [singularity exec -e -B /share/app/PCGR/data-20220118:/data -B /path/to/outdir:/outdir -B /path/to/vcfdir:/vcfdir -B /path/to/cnadir:/cnadir /share/app/PCGR/pcgr-v0.10.7.sif /opt/mambaforge/envs/pcgr/bin/pcgr --pcgr_dir /data --genome_assembly grch38 --input_vcf /vcfdir/test.vcf.gz --sample_id test --output_dir /outdir --vep_regulatory --estimate_tmb --estimate_msi_status --estimate_signatures --tumor_dp_tag TDP --tumor_af_tag TVAF --control_dp_tag NDP --control_af_tag NVAF --call_conf_tag TAL --input_cna /cnadir/test.seg.tsv --tumor_site 9 --tumor_purity 0.37 --tumor_ploidy 3.3 --vcf2maf --show_noncoding --assay WGS --include_trials --force_overwrite --no_docker] the complete command you used to invoke pcgr (including all explicit options)
- [2022-01-19 22:16:10 - pcgr-report-generation - INFO - Generating report data for copy number segment file /cnadir/test.seg.tsv 
Error: Column `intogen_drivers` not found in `.data`] the **full** error message

Whenever possible, please also provide links to query VCF file.

**Additional context**

**Comment by sigven** [comment]
Hi,

We are still testing and debugging the new version. It will be announced on the main page when a new release is ready for download and use.

Kind Regards,
Sigve
