### ISSUE TITLE
Integrate vcf2maf

### ISSUE THREAD

**Issue by apastore** [sigven/pcgr#17]
Hi Sigven, I realy like your pcgr. I was wondering if would not be useful to output a maf file that can be used for downstream analysis. I am currently using vcf2maf. 

Do you think it may make sense to have this in integrated in your package?

Thanks

**Comment by sigven** [comment]
Hi @apastore, thanks for your message. Generation of MAF file is however already part of PCGR (all output files are outlined at the very bottom of [README](https://github.com/sigven/pcgr/blob/master/README.md)). If you look at all the output files for your run, do you not see any file with a _.maf_ suffix?

**Comment by apastore** [comment]
The reason why I rerun vcf2maf is that I am not able to set a specific Isoform to report 
https://github.com/mskcc/vcf2maf/blob/master/data/isoform_overrides_uniprot
The isoform picked is not the one usually reporter for MYD88 


Also the ExAC and GnomAD are not filtered for know somatic sites
https://github.com/mskcc/vcf2maf/blob/master/data/known_somatic_sites.bed
a lot of DNMT3a and TET2  somatic variant are reported in ExAC and GnomAD.

**Comment by sigven** [comment]
Hi,

Although I am not sure what your exact needs are, I will integrate vcf2maf in the PCGR pipeline in development. If you can share an example VCF with me and see whether the output that is produced is satisfactory, we can include it in the upcoming release.

**Comment by apastore** [comment]
I am using the ensemble vcf from bcbio as an input for pcgr.

I will aslo rellay appreciate any suggestion on how to retain the paired normal DP and AF.

At the moment I only keep the Tumor values.

Thanks a lot!
Alessandro

**Comment by sigven** [comment]
VCF to MAF conversion using https://github.com/mskcc/vcf2maf is implemented, and will be part of the upcoming PCGR release.
