### ISSUE TITLE
PCGR data bundle is not compliant with the software version

### ISSUE THREAD

**Issue by adbeggs** [sigven/pcgr#176]
Whenever you encounter an error, please also include:

- [ 0.10.14] Version of PCGR.
- [grch38 ] Genome build (grch37/grch38).
- [ ] the complete command you used to invoke pcgr (including all explicit options)
- [2022-02-06 12:15:16 - pcgr-validate-arguments-input - ERROR - The PCGR data bundle is not compliant with the software version - please download the latest software and data bundle (see https://github.com/sigven/pcgr for instructions) ] the **full** error message

Whenever possible, please also provide links to query VCF file.

**Additional context**

I have placed pcgr into a conda instance running on singularity on our HPC - it works find but the link to the data bundle is out of date - do you have newer links please?

**Comment by sigven** [comment]
Hi Andrew,
Thanks for reaching out! We are very close to making the version you have in your conda instance official (that is, as announced through the master branch on https://github.com/sigven/pcgr, all the latest developments are currently in a dedicated development branch (https://github.com/sigven/pcgr/tree/dev). We'll try to tag the versions in the development branch more explicitly as _dev_ versions moving forward, you are not the first one who have installed these latest (but not officially released) versions :-)

You are of course free to download the latest bundle, which will go into release shortly, please have a look at the new website with updated installation instructions and link to the databundle: https://sigven.github.io/pcgr/articles/installation.html.

Sorry for the inconvience,

regards,
Sigve

**Comment by sigven** [comment]
Btw, the new Conda release of PCGR will also give you direct access to CPSR (cancer predisposition analysis reporting):
https://github.com/sigven/cpsr/tree/dev
https://sigven.github.io/cpsr

best,
Sigve

**Comment by adbeggs** [comment]
Thank you.. just pushing through a couple of issues with it, will record as new issues
