### ISSUE TITLE
cyvcf2 not bundled with latest pcgr vesion

### ISSUE THREAD

**Issue by adbeggs** [sigven/pcgr#177]
Just to flag up - cyvcf2 does not bundle with the default pcgr conda - works fine when add it in the Environment.yml

**Comment by pdiakumis** [comment]
@adbeggs thanks for the report. Yep, that's intentional. The `pcgr` conda pkg bundles just the Python code. The dependencies (`cyvcf2`, `ensemble-vep` etc.) get brought in via the environment file.

**Comment by adbeggs** [comment]
It's more if you build a singularity image, I exported the environment.yml from a machine where I installed it with conda. When I build the singularity image it builds the conda environment correctly but cyvcf2 seems to be left out in the environment.ym

**Comment by pdiakumis** [comment]
@adbeggs may I ask which commands you're using to set up the environments?
I think the simplest way to install them is with:

```
PCGR_VERSION="0.10.14"
PCGR_REPO="https://raw.githubusercontent.com/sigven/pcgr/v${PCGR_VERSION}/conda/env/lock/"
PLATFORM="linux" # or "osx"

mamba create --file ${PCGR_REPO}/pcgr-${PLATFORM}-64.lock --prefix ./pcgr
mamba create --file ${PCGR_REPO}/pcgrr-${PLATFORM}-64.lock --prefix ./pcgrr
conda activate ./pcgr

# test that it works
pcgr --version
```

Using the `--prefix` option installs those envs in the local directory, but I suppose you could also use `-n/--name pcgr` to install those in your central conda location.

Thanks for filing these issues, very helpful!
