### ISSUE TITLE
Error with TCGA vcf

### ISSUE THREAD

**Issue by nrosewick** [sigven/pcgr#19]
Hi,

I tried to annotate some vcf from TCGA using pcgr : 
`python /home/user/tools/pcgr.py --input_vcf tcga.vcf /home/user/tools/pcgr-0.5.3 ./ /home/user/tools/pcgr-0.5.3/pcgr_configuration.toml tcga_sample`
It gives me an error : 
```
2018-02-01 09:22:04 - pcgr-validate-input - INFO - STEP 0: Validate input data
2018-02-01 08:22:04 - pcgr-validate-input - INFO - Validating VCF file with EBIvariation/vcf-validator
2018-02-01 08:22:05 - pcgr-validate-input - ERROR - 
2018-02-01 08:22:05 - pcgr-validate-input - ERROR - According to the VCF specification, the VCF file (/workdir/input_vcf/d45d836f-98d1-4910-87d4-87e111cdcb77.vcf) is NOT valid:
ERROR: Line 37: SAMPLE metadata Genomes is not a valid string (maybe it contains quotes?)
ERROR: Line 2819: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2820: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2821: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2822: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2823: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2824: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2825: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2826: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2827: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 2828: Format is not a colon-separated list of alphanumeric strings
.
.
.
```

Here's the line that gives the errors : 

line 37
`##SAMPLE=<ID=NORMAL,SampleName=TCGA-AB-2802-11B-01W-0728-08,File=/var/lib/cwl/job762068026_input_JCMquC/C317.TCGA-AB-2802-11B-01W-0728-08.3_gdc_realn.bam>`

line 2819 -> 2828
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr1	634553	rs368347679	G	A	.	germline_risk;panel_of_normals;t_lod_fstar	DB;ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=0.902;TLOD=6.25	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:24,0:0.00:0:0:.:718,0:10:14	0/1:3,2:0.500:0:2:0.00:55,65:2:1
chr1	1752908	rs150880809	C	CCCT	.	germline_risk;panel_of_normals	DB;ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=0.925;RPA=9,10;RU=CCT;STR;TLOD=13.21	GT:AD:AF:ALT_F1R2:ALT_F2R1:QSS:REF_F1R2:REF_F2R1	0/0:3,0:0.00:0:0:31,0:2:1	0/1:0,5:1.00:4:1:0,117:0:0
chr1	1825425	rs76273614	T	C	.	alt_allele_in_normal;germline_risk;panel_of_normals	DB;ECNT=1;HCNT=2;MAX_ED=.;MIN_ED=.;NLOD=3.45;TLOD=32.88	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:177,35:0.162:21:14:0.600:5734,468:101:76	0/1:204,57:0.156:32:25:0.561:6528,1106:118:86
chr1	1981144	rs4648742	T	G	.	germline_risk;panel_of_normals	DB;ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=0.903;TLOD=6.85	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:4,0:0.00:0:0:.:113,0:0:4	0/1:2,3:0.500:0:3:0.00:63,96:1:1
chr1	2193952	.	C	A	.	germline_risk;t_lod_fstar	ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=2.10;TLOD=5.00	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:7,0:0.00:0:0:.:195,0:3:4	0/1:14,3:0.133:0:3:1.00:422,82:8:6
chr1	2932308	.	A	T	.	germline_risk;t_lod_fstar	ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=1.46;TLOD=5.55	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:6,0:0.00:0:0:.:167,0:4:2	0/1:2,2:0.500:1:1:0.500:66,58:1:1
chr1	3270045	rs35838176	T	A	.	germline_risk;panel_of_normals	DB;ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=0.602;TLOD=7.55	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:4,0:0.00:0:0:.:113,0:4:0	0/1:0,2:1.00:1:1:0.500:0,66:0:0
chr1	3838843	.	C	A	.	t_lod_fstar	ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=5.42;TLOD=4.28	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:18,0:0.00:0:0:.:586,0:5:13	0/1:17,2:0.105:0:2:1.00:574,61:9:8
chr1	4211829	.	G	T	.	t_lod_fstar	ECNT=1;HCNT=2;MAX_ED=.;MIN_ED=.;NLOD=2.41;TLOD=4.88	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/0:8,0:0.00:0:0:.:268,0:3:5	0/1:9,2:0.200:2:0:1.00:297,61:3:6
chr1	4321000	rs3058085	A	ATCT	.	germline_risk;panel_of_normals	DB;ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=0.908;RPA=1,2;RU=TCT;STR;TLOD=13.49	GT:AD:AF:ALT_F1R2:ALT_F2R1:QSS:REF_F1R2:REF_F2R1	0/0:4,0:0.00:0:0:120,0:1:3	0/1:0,3:1.00:2:1:0,89:0:0

```

Any ideas ? I can send you a minimal reproducible example if you want.

Thank

**Comment by sigven** [comment]
Hi @nrosewick, 

Thanks for your message. Would you mind sharing your input VCF (Dropbox etc.)? 

As [others have noted](https://github.com/sigven/pcgr/issues/15), the VCF-validation step can be too strict in some ways, but also [necessary for other purposes](https://github.com/sigven/pcgr/issues/16). Paradoxically, most VCFs from large sequencing consortia (TCGA, ICGC etc.) produce VCF files that fail the validation step :-)
Note that in the upcoming release, users can configure whether to ignore/keep the VCF validation step. 

Looking at the errors on line 2819 and forward on, it seems that your genotype fields are incorrectly formatted, they should be alphanumeric, and I thus suspect that the inclusion of the underscore (`_`) is the problem (e.g. `ALT_FIR2`,`ALT_F2R`). You could try to remove the underscore to see if that helps. The first error at line 37 I need to look more closely into when I receive the VCF.

**Comment by nrosewick** [comment]
Hi @sigven 

Here's the vcf : https://drive.google.com/open?id=1CF2dj75z0i82EIAiWj09FR2dY0t_9VXr

Do you have a estimated release date for the next version ? I already checked in your code and could delete the vcf validation step from your code and try again.

Thank you for your fast answer

**Comment by sigven** [comment]
HI @nrosewick,
Sorry for the late reply. I will hopefully have a new release by the end of February. I'll make sure to test your VCF properly by that time.

regards,
Sigve

**Comment by nrosewick** [comment]
Hi Sigve,

Thank you for your answer. Do you have any idea about the release date of the new version of pcgr ?

best

**Comment by sigven** [comment]
Hi Nicolas,
Thanks for your reminder. There has been delays on my side, so the (tentative) plan is to have a new release by March. Truly sorry about the delay.

best,
Sigve

**Comment by nrosewick** [comment]
Hi Sigve,

Thank you for your return. Great for the next version ! 

I hope Mutect2 vcf will be ok for pcgr.

Best,
Nicolas

**Comment by sigven** [comment]
0.6.0 is now ready for testing.
