### ISSUE TITLE
expand Clinical biomarkers  

### ISSUE THREAD

**Issue by user-tq** [sigven/pcgr#202]
This is an amazing project. I learned a lot from it.

I noticed this

```
Clinical biomarkers included in PCGR are limited to the following:
Evidence items for specific markers in CIViC must be accepted (submitted evidence items are not considered)
Markers reported at the variant level (e.g. BRAF p.V600E)
Markers reported at the codon level (e.g. KRAS p.G12)
Markers reported at the exon level (e.g. KIT exon 11 mutation)
Within the [Cancer bioMarkers database (CGI)], only markers collected from FDA/NCCN guidelines, scientific literature, and clinical trials are included (markers collected from conference abstracts etc. are not included)
Copy number gains/losses
```
It seems to lose some info.

for instance
```
MET  Exon 14 Skipping Mutation
BRCA2 Loss-of-function
TP53 Overexpression
```
These cannot be converted to genomic variants through TransVar.But they should not be discarded.

I tried to build a complete local database containing the relationship between mutations and drugs. The result annotated in vep/annovar is used as the query input.
When querying the civic database, I found that there are so many variants that it seems impossible to establish a unified set of rules.
Besides, I don't know what the result of VEP/annovar annotation is, so I can't build a dictionary to convert it into the input field of the database.

Do you have any ideas and suggestions about this?

**Comment by user-tq** [comment]
thanks，I learned a lot again

**Comment by sigven** [comment]
Hey @user-tq,

Was looking a bit more into MET exon 14 skipping mutations. It seems that variants (SNVs) located at the canonical splice site on one end (of the adjacent intron) are attributed to exon skipping (NM_000245.2:c.3028+1G and NM_000245.2:c.3028+2T):

https://brb.nci.nih.gov/cgi-bin/splicing/splicing_main.cgi

This knowledge should be curated and shown in PCGR. Thanks for input!

best,
Sigve
