### ISSUE TITLE
Most columns are empty within MAF

### ISSUE THREAD

**Issue by weichisyu** [sigven/pcgr#203]
Hi Sigven,

Thanks for this wonderful project.
Recently I use PCGR to get both HTML report and MAF.

It seems that the file input to vcf2maf isn't annotated, so most column are empty in the final MAF. 
I found that it could get the MAF with annotated information by put either `.pcgr_ready.vep.vcf` or `.pcgr_acmg.grch38.vcf` which already annotated by PCGR into vcf2maf. 
Is it possible to have a true/false argunment let user make PCGR put those annotated vcf into vcf2maf? Or passing the annotated vcf into vcf2maf directly within PCGR?

**Comment by sigven** [comment]
Dear @weichisyu,

Thanks for your interest in PCGR, I am happy you find it useful:-)

I will go through the MAF generation to see how we can populate the MAF with more data. You essentially want more of the data provided from PCGR annotation in your MAF, right? 

best,
Sigve

**Comment by weichisyu** [comment]
Dear @sigven 

For now, the input for vcf2maf within PCGR is unannotated vcf and using `--inhibit-vep` arg to turn the VEP annotation off. So most columns in the final MAF are empty (e.g. HGVSc,gnomAD data...etc.) and the Hugo_Symbol column is always _**Unknown**_.
If turn the --inhibit-vep arg on or let the VEP annotated vcf as input to vcf2maf (e.g.  `.pcgr_ready.vep.vcf` or `.pcgr_acmg.grch38.vcf`). Then the final MAF will get that information and this MAF is enough for my downstream analysis.

But, it sounds great if the MAF could have more of the data provided by PCGR annotation. (It means adding more columns right?)
The vcf2maf seems to generate a fixed header and extracts the information from annotated vcf to put into it. I am unsure whether vcf2maf could accept the information differently from their default header.
Although I am not familiar with Perl. But I would take some time trying to read the code within vcf2maf, to figure out whether it has other functions to take more customize annotated information. It seems to have some hint between line 533 to line 557 in vcf2maf.pl.

best,
Weichi

**Comment by sigven** [comment]
Dear Weichi,

I think your suggestion regarding feeding vcf2maf with the VEP-annotated VCF might be the best solution, I will try to set this up.

best,
Sigve
