### ISSUE TITLE
Methods and scripts to make database files

### ISSUE THREAD

**Issue by plsysu** [sigven/pcgr#21]
Hi, PCGR is a great tool for clinical cancer genomics analysis.

I want to know how to make these database files in  the the data bundle, like pcgr_data.rda and other files.
I want to add/modify some data sets to meet my needs.
 
Is there any scripts to automatically generate these bundle files?

thanks !

**Comment by sigven** [comment]
Hi Peng,
Thanks for your interest in PCGR. As of now, I have not made the code and scripts for cleaning raw datasets available, since these are not organized and polished in a sufficient manner. I will consider to have these released in the future. Meanwhile, I suggest you contact me directly through email with your exact needs/specific databases, and I can try to support you with what I have.

regards,
Sigve

**Comment by plsysu** [comment]
Hi Sigve,

Thanks for your reply on my questions.

When doing CNV annotation，PCGR compares a query segment against the genecode  database. However, the selected items of database is much smaller than the raw database (100000 vs 2620000 ).

My questions is how to select  the genecode database to make   cancer gene CNV annotation the right way ?

regards,
Peng
发件人: Sigve Nakken <notifications@github.com>
发送时间: 2018年3月9日 16:18
收件人: sigven/pcgr <pcgr@noreply.github.com>
抄送: Peng Li <peng-li@outlook.com>; Author <author@noreply.github.com>
主题: Re: [sigven/pcgr] Methods and scripts to make database files (#21)


Hi Peng,
Thanks for your interest in PCGR. As of now, I have not made the code and scripts for cleaning raw datasets available, since these are not organized and polished in a sufficient manner. I will consider to have these released in the future. Meanwhile, I suggest you contact me directly through email with your exact needs/specific databases, and I can try to support you with what I have.

regards,
Sigve

**Comment by sigven** [comment]
Hi,

Please note that the number of records you refer to (~262,000) in the comprehensive GENCODE annotation set comprises both the full-length transcripts and individual exons. PCGR does not annotate towards exons, but full-length transcripts only. Furthermore, PCGR does not use the comprehensive set for annotation, but rather the "basic" GENCODE annotation set, see [GENCODE FAQ number 4](https://www.gencodegenes.org/faq.html)

Also note that the while the PCGR HTML report highlights protein-coding transcripts (of potential clinical significance) the CNA annotation file should include the intersection of the query CNA segments with any transcript types (noncoding RNA etc) that are part of the GENCODE basic annotation set. 

I hope that may clarify things. Let me know if some parts are still unclear.

regards,
Sigve

**Comment by plsysu** [comment]
I got it. Thanks a lot !
