### ISSUE TITLE
Regarding CNV analysis on germline VCF

### ISSUE THREAD

**Issue by AidanGCr** [sigven/pcgr#219]
Hello,

I understand that CPSR does not include an analysis framework as of now for CNV / SV analysis. However, CNV analysis is done within PCGR. I was wondering, would running a germline sample in tumor-only mode allow for effective prioritization of CNV calls? Of course, this would be with relevant settings disabled such as the following (as mentioned in the readme): 

    --exclude_dbsnp_nonsomatic
    --exclude_likely_het_germline
    --exclude_likely_hom_germline
    --exclude_nonexonic

Thanks,
Aidan

**Comment by sigven** [comment]
Dear Aidan,

Thanks for your question. Note that germline variants in the form of copy number is not a particularly frequent phenomenon when it comes to cancer predisposition, this is why this is currently omitted in the CPSR input. Also not that the above filtering strategy only works for SNVs/InDels, and is thus it will not really be applicable for filtering a germline sample. PCGR only accepts somatic CNA calls - no filtering is performed on those.

kind regards,
Sigve

**Comment by AidanGCr** [comment]
Hi Sigve, 

I see, thank you for clarifying about the filtering. Considering, that the SV/CNV filtering is done beforehand on my end, with data then being transformed into the tsv format, PCGR would then classify all CNV calls it could, with the assumption of them all being somatic, correct? 

Thanks,
Aidan

**Comment by AidanGCr** [comment]
Great! I look forward to seeing the updates! 

Thanks,
Aidan
