### ISSUE TITLE
Google drive link for new data bundles not working

### ISSUE THREAD

**Issue by zacshi** [sigven/pcgr#23]
pcgr.databundle.grch37.20180422.tgz was not downloadable. 

![screenshot 2018-04-27 11 52 38](https://user-images.githubusercontent.com/12676004/39372138-928a9b48-4a11-11e8-89da-e9af4e7bb7f8.png)

**Comment by sigven** [comment]
The URL you are referring to seems unfamiliar to me. Where did you get this?

The URL for grch37 is [https://drive.google.com/open?id=1tOyPmzgXkSZjPJQOojFQxUP8JlQuQqLq](https://drive.google.com/open?id=1tOyPmzgXkSZjPJQOojFQxUP8JlQuQqLq)
