### ISSUE TITLE
VCF validation can be turned off - how?

### ISSUE THREAD

**Issue by leiendeckerlu** [sigven/pcgr#25]
:)

**Comment by sigven** [comment]
Hi,

Use a TOML configuration file to run your workflow, e.g. [this](https://raw.githubusercontent.com/sigven/pcgr/master/pcgr.toml) (vcf-validation is turned off here).

In [STEP 4: Configure PCGR](https://github.com/sigven/pcgr#step-4-configure-pcgr) there is also a link to [how the configuration settings work](http://pcgr.readthedocs.io/en/latest/input.html#pcgr-configuration-file). Please read this.

Sigve
