### ISSUE TITLE
Typo in variant_classification.html

### ISSUE THREAD

**Issue by skanwal** [sigven/pcgr#255]
Hello,

Noted a small typo in [https://sigven.github.io/pcgr/articles/variant_classification.html](https://github.com/sigven/pcgr/blob/14400cf2857ce19a1d7a755dd98eb212261129f5/pcgrr/vignettes/variant_classification.Rmd#L12)

> as well as**tumor suppressor genes subject to homozygous deletions**.

as well as **tumor suppressor genes subject to homozygous deletions**.

**Comment by sigven** [comment]
Hi @skanwal,
Thanks for informing about it. Will set up a fix. Closing this issue for now.

kind regards,
Sigve
