### ISSUE TITLE
deconstructSigs and hg38

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#27]
Hi Sigve, 

Thanks for the new version and especially hg38 support! Worked fantastic, however when tried to enable `mutational_signatures`, I ran into this issue:

```
2018-05-03 01:09:56 [INFO] Identifying weighted contributions of known mutational signatures using deconstructSigs
2018-05-03 01:09:56 [INFO] deconstructSigs normalization method ('tri.counts.method'): genome
Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  :
  solving row 14999: 'allow.nonnarrowing' is FALSE and the supplied start (180930244) is > refwidth + 1
Calls: <Anonymous> ... .extractFromBSgenomeSingleSequences -> solveUserSEW -> .Call2 -> .Call
Execution halted
```

Not sure, but this might to be coming from deconstructSigs not fully supporting hg38? There is a fork that has this fix: https://github.com/temizna/deconstructSigs/commit/596cec6f0db37d2796806b3eae60ccf0a3bfd4e9

Maybe as a quick fix, PCGR could pull the fixed deconstructSigs branch rather than the main one. Though no rush for us in UMCCR - currently we generate mutational signature separately. But would be nice to have all in PCGR in the future!

Vlad

**Comment by vladsaveliev** [comment]
Worried that the object `bsg` is not used in `signature_contributions_single_sample` function: https://github.com/sigven/pcgr/blob/master/src/R/pcgrr/R/mutational_signatures.R#L13

And it actually not passed here: https://github.com/sigven/pcgr/blob/master/src/R/pcgrr/R/mutational_signatures.R#L80-L85

**Comment by sigven** [comment]
Hi Vlad,
Thank you so much for reporting this! An obvious mistake in my code. I'll get back to you for testing a fixed version.

Sigve

**Comment by vladsaveliev** [comment]
And while we are on it, attaching one more. This one crashes with the following error:

```
2018-05-03 15:11:11 - pcgr-summarise - INFO - Converting VCF to TSV with https://github.com/sigven/vcf2tsv
Traceback (most recent call last):
  File "/pcgr/vcf2tsv.py", line 259, in <module>
    if __name__=="__main__": __main__()
  File "/pcgr/vcf2tsv.py", line 23, in __main__
    vcf2tsv(args.query_vcf, args.out_tsv, args.skip_info_data, args.skip_genotype_data, args.keep_rejected_calls, args.compress, args.print_data_type_header)
  File "/pcgr/vcf2tsv.py", line 220, in vcf2tsv
    out.write('\t'.join(line_elements) + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 6803: ordinal not in range(128)
```

Again, does not pass validation, so might be something wrong with the VCF. But I can't reproduce the error by running `vcf2tsv` manually neither with the input VCF, nor with the resulting `.pass.vcf.gz`.

[COLO829__COLO829T-normal.zip](https://github.com/sigven/pcgr/files/1970257/COLO829__COLO829T-normal.zip)

**Comment by sigven** [comment]
Hi again Vlad,

I did not see any CNV calls in your zip, but I believe I have now fixed the bugs you encountered in 0.6.1 (deconstructSigs for hg38, and an ASCII-encoding issue in the vcf2tsv transformation (the lack of proper encoding caused a mistake for "Café-au-lait_macules_with_pulmonary_stenosis":-))

Output files for SNVs/InDels in COLO829 can be [downloaded here](https://drive.google.com/open?id=1lIwqVqGOhkPZDbKCUdOsHW4bzFJEoWEQ).

A couple of comments to your run and config (not sure how carefully this was configured, but anyways):

- the target size should refer to the *coding* region, implying that this will be similar for WES/WGS, and limited to approx 35-40 Mb (Ideally one should get hold at the size of the *callable* coding target, correcting for uneven coverage across the regions that have been sequenced)
- although the VCF works without validation, the vcf2tsv found an additional bug in one of your pre-existing INFO tags (clinvar_sig, which is a mix of String/Flag), take a look at the log file (*COLO829.pcgr_acmg.log*)
- from the allelic distribution plot (and the signatures) in your report this clearly seems like a tumor-only run, in that case it should be pre-filtered or run with *tumor_only=true*

**Comment by vladsaveliev** [comment]
Sigve, thanks for the reply, really appreciate the quick fixes. `Café-au-lait_macules_with_pulmonary_stenosis` is hilarious. There should be a special place in hell for people creating such kind of identifiers 😆 

Sorry, I was in a rush and forgot include the CNV file, though it's irrelevant; also you are absolutely right about the target size, in fact PCGR warned me about that and stopped running, so I changed the value back to 36 for the rerun (Nice error handling btw!). However for some reason I accidentally sent you the bad version of the toml.

**Comment by vladsaveliev** [comment]
Speaking about germline, should we be running this isntead? https://github.com/sigven/pcgr_predispose

**Comment by akhtar4ever** [comment]
Hi Sigve,

I turned off the input validation and ran the tool, and facing somewhat similar issue , exact error mentioned below:

2018-05-04 07:10:41 [INFO] deconstructSigs normalization method ('tri.counts.method'): default
Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 15428: 'allow.nonnarrowing' is FALSE and the supplied start (180947483) is > refwidth + 1
Calls: <Anonymous> ... .extractFromBSgenomeSingleSequences -> solveUserSEW -> .Call2 -> .Call
Execution halted


I have turned off input validation as it was not processing the vcf file and flagging below error:
2018-05-04 07:22:41 - pcgr-validate-input - INFO - Validating VCF file with EBIvariation/vcf-validator
2018-05-04 07:22:42 - pcgr-validate-input - ERROR - 
2018-05-04 07:22:42 - pcgr-validate-input - ERROR - According to the VCF specification, the VCF file (/workdir/input_vcf/TOtB_5724_index13_AGTCAA_L001-L002_001.tnscope_filtered_GRCh38.vcf) is NOT valid:
ERROR: Line 254: Format is not a colon-separated list of alphanumeric strings
ERROR: Line 255: Format is not a colon-separated list of alphanumeric strings
This continued till last line of vcf file.

Any help/suggestion would be appreciated.

Thanks

**Comment by akhtar4ever** [comment]
Thanks Sigve,

Thanks for the fixes.
Currently using the latest released code 0.6.2 , but facing below issue:

2018-05-11 07:26:59 [INFO] Identifying weighted contributions of known mutational signatures using deconstructSigs
2018-05-11 07:26:59 [INFO] deconstructSigs normalization method ('tri.counts.method'): default
Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 405: 'allow.nonnarrowing' is FALSE and the supplied start (139391184) is > refwidth + 1
Calls: <Anonymous> ... .extractFromBSgenomeSingleSequences -> solveUserSEW -> .Call2 -> .Call
Execution halted

Any help/suggestion would be appreciated.

Thanks
Akhtar

**Comment by sigven** [comment]
Ah, I see. I need your input (VCF + the config file) to do error-checking. Would you be able to share that with me?

**Comment by akhtar4ever** [comment]
Hi Sigve,

I have specified the build, command used is:
** python /home/cwtools/pcgr-0.6.2/pcgr.py --input_vcf test_new.vcf /home/cwtools/pcgr-0.6.2 /home/cwtools/for_upload/test_new grch38 /home/cwtools/pcgr-0.6.2/pcgr.toml  test_new --force_overwrite**
config file is the default toml file in which I have just changed validation to false.

**Comment by akhtar4ever** [comment]
Hi Sigve,

Apologies for the delay.

Attached the vcf and config file.

Thanks
Akhtar

**Comment by akhtar4ever** [comment]
Hi Sigve,

The files were not getting uploaded, so zipped them.

[for_pcgr_share.zip](https://github.com/sigven/pcgr/files/2000480/for_pcgr_share.zip)
Please find the zip file, which contains vcf and toml file I used.

Let me know if anything else is required.

Thanks
Aktar

**Comment by sigven** [comment]
Hi Akhtar, 

I asked previously if you had specified the correct build (GRCh37/GRCh38) for your input, making sure that the build you specify is matching your input data. In your test case (`test_new.vcf`), this is not  GRCh38, and this is why it's failing with the command you specified above (the huge number of warnings you recieve during VEP annotation should also give you a hint that the assembly you specified is wrong). 

I used GRCh37, and it ran with no errors. You can see from line 4 in your VCF that `test_new.vcf` is hg19/GRCh37:
`##reference=file:///b/LF1/seq/data_external/bwahg19/hg19_basicChromosomes.fa`

Although PCGR in principle could make an assembly check for the input, I believe the users should carry the main responsibility for making sure that there is a correspondence between the build/assembly that is specified and the actual build/assembly of the input files. It's also highly appreciated if this matter is interrogated before any issues are filed.

kind regards,
Sigve

**Comment by akhtar4ever** [comment]
Thanks a lot Sigve for your findings.
Will make a note of it.

Appreciate your efforts and quick response.


Thanks
Aktar
