### ISSUE TITLE
Error while parsing vcf from MuTect2

### ISSUE THREAD

**Issue by patidarr** [sigven/pcgr#28]
Hi, I got following error while parsing a file from MuTect2

ERROR: Line 433: Format is not a colon-separated list of alphanumeric strings

Here is my format string
GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1  
0/1:0,16:1.000:10:6:0.375:0,455:0:0

are there particular tags you are looking for?

Thanks,
Rajesh

**Comment by sigven** [comment]
Hi, 

Unfortunately, MuTect2 produces a VCF file that does not adhere to the VCF format restrictions (as checked by VCF-validator). Although not recommended, VCF validation can be turned off. I have responded to a similar issue [previously](https://github.com/sigven/pcgr/issues/22)
