### ISSUE TITLE
Few Question about input

### ISSUE THREAD

**Issue by patidarr** [sigven/pcgr#29]
Hi,

Amazing tool. Thanks for developing and investing your time into it.

I am able to run the tool on a few of my own samples within few minutes of installation, which shows, amazingly easy and clear documentation.

I have a couple of questions:
- An unannotated, single-sample VCF file (>= v4.2) with called somatic variants (SNVs/InDels)
     Can AD/DP be extracted from FORMAT? I provided single sample vcf file but I don't have AD/DP/AF in INFO column and most callers does not do that either. but sample column mostly do have read level information so it would be very helpful if can be used. else I have to write another script to recode vcf to the format you require.
- Some callers like strelka have different tag names for AD/DP etc, can these tags be defined in config file or command line?
- Can diagnosis (cancer type) be a command line input? I work on many different cancer types and it would be helpful if I don't have to edit config file before running every other sample.

Thanks a ton,
Rajesh

**Comment by sigven** [comment]
Hi Rajesh,

Thank you for your comments. Your questions are indeed very relevant, some of which have been discussed extensively by other users in a closed [issue](https://github.com/sigven/pcgr/issues/12). Let me try to address your questions, point by point:

* You are correct, the DP/AF information for tumor/control is usually present in the FORMAT (genotype) column of the VCF (and can thus be extracted here). However, as I have argued previously (and which have received support by some users), the variety of somatic mutation callers choose very different ways to report this (if you have experience working with different callers, I am sure you can agree to this). This is even further complicated by how different callers handle multi-allelic calls, particularly when it comes to the data in the FORMAT column (I have seen a lot of weird inconsistencies here). That being said, with the help of @choosehappy, we started to draft some code for parsing this information from different callers, have a look at these gists ([#1](https://gist.github.com/sigven/1343995dd18b857ae71bf2963138b11c),[#2](https://gist.github.com/choosehappy/d2eba4bfc7fb01b755eb8ecccc55b597)). To sum up, automatic retrieval of DP/AF information from the FORMAT columns is not integrated in PCGR. We kindly ask the user to move this information to the INFO column in a preprocessing step, the specific AF/DP tags that is appended can then be referenced in the PCGR configuration file.
* I believe I have addressed this in my first point (make your own custom INFO tags)
* This one, cancer type as a command line option, is definitely something i will consider. This would for sure speed up analysis, and save the creation of multiple config files. I have added this as an enhancement.

regards,
Sigve
