### ISSUE TITLE
general clinical sequence variants

### ISSUE THREAD

**Issue by rjsicko** [sigven/pcgr#3]
Hi, 
Thanks for providing this tool and source code. The output looks great!

Is the license for this software open? If so, any guidance on the modifying the software to generate a summary of general clinical sequencing results? I'm thinking generate a report of "pathogenic" variants by [ACMG/AMP guidelines](https://www.ncbi.nlm.nih.gov/pubmed/25741868) Most of the annotation still apply, it's just tweaking the interpretation and report generation. I just found [InterVar ](https://github.com/WGLab/InterVar) and this might be able to provide the logic for the interpretation portion.

**Comment by sigven** [comment]
Hi,

Thanks for the feedback :-) I am working on selecting an open source licence. 

Regarding your question to generate report for pathogenic variants etc. please bear in mind that PCGR is intended for somatic variants found in a given tumor, and not germline variants, which the ACMB/AMP guidelines are intended for (as far as I have understood). But you are right, most of the annotation that are found in PCGR will be relevant also in a germline setting. Either way, is not InterVar what you are looking for? Or is it  the combination of InterVar + interactive report you want to obtain?

**Comment by rjsicko** [comment]
Exactly, InterVar for classifying and PCGR for generating an interactive report is what I'm looking for. I prefer your method of annotation with vcfanno vs annovar (InterVar uses annovar under the hood) as well since it is easy to update source annotations. 

I don't work with cancer analysis so I'm not sure how reliable the standards are, but ACMG/AMP has recently released standards for somatic variants (https://www.ncbi.nlm.nih.gov/pubmed/27993330).

**Comment by sigven** [comment]
Hi,

I am in the process of expanding PCGR for cancer predisposition analysis:
https://github.com/sigven/pcgr_predispose

This is very preliminary, yet an effort to also have reports for germline variants. 

FYI and if you are not aware, there is an effort within the Ding lab for automatic classifications of germline variants based on ACMG/AMP guidleines:
https://github.com/ding-lab/CharGer

CharGer, also cancer-focused, was utilized in a recent [Cell paper](https://www.ncbi.nlm.nih.gov/pubmed/29625052)

I am closing this issue for now.

regards,
Sigve
