### ISSUE TITLE
Wrong percentage reported regarding the screening against gnomAD

### ISSUE THREAD

**Issue by zacshi** [sigven/pcgr#31]
Just noticed a line in the report saying:
"Exclusion of variants found in gnomAD: 1780 ( 1780 % of unfiltered calls)"
Number of variants and the percentage look exactly the same. Could be a easily fixed, I assume. Please let us know which script we may change to correct this. Thanks.

**Comment by sigven** [comment]
Hi,
Thanks a lot for noticing! I just fixed it. Correct fraction will be reported in the upcoming release, in which some other bugs are also fixed.
regards,
Sigve
