### ISSUE TITLE
CNA file 0-based or 1-based

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#32]
Hi Sigve,

Should CNA file be 1-based, or 0-based? 

I'm having this:

```
2018-05-07 11:04:46 - pcgr-validate-input - ERROR - Detected wrongly formatted chromosomal segment - 'Start' or 'End' is less than or equal to zero (17:0-567999)
```

On this line:

```
grep 567999 COLO829__COLO829T-somatic.tsv
17      0       567999  0.0522327
````

I guess it should be 1-based? Would be great to clarify in the docs!

Thanks again,
Vlad

**Comment by sigven** [comment]
Yeah, they should be 1-based. I am updating the docs, so that it reflects this choice. 
Thanks for reporting,
Sigve

**Comment by vladsaveliev** [comment]
Awesome, thanks for confirming :)
