### ISSUE TITLE
Error in CNV reporting

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#34]
Hi Sigve,

I'm getting an error with the CNA file attached:

```
pcgr.py --input_cna V-PH-19__PRJ170210_V-PH-19T-somatic-cna.tsv --input_vcf V-PH-19__PRJ170210_V-PH-19T-somatic.vcf.gz . output grch37 pcgr_configuration_somatic.toml V-PH-19__PRJ170210_V-PH-19T-somatic --docker-uid root
...
2018-05-14 06:01:10 [INFO] Generating report data for copy number segment file /workdir/input_cna/V-PH-19__PRJ170210_V-PH-19T-somatic-cna.tsv
Error in `$<-.data.frame`(`*tmp*`, event_type, value = NA) :
  replacement has 1 row, data has 0
Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> $<- -> $<-.data.frame
Execution halted
```

The inputs tarball:
[umccr_error.zip](https://github.com/sigven/pcgr/files/1999493/umccr_error.zip)

What might be the reason? I cannot reproduce it for other CNA files.

**Comment by sigven** [comment]
Hi Vlad,

Thanks. Download the latest [pcgr.py](https://github.com/sigven/pcgr/blob/master/pcgr.py) script,  pull the latest docker image (`docker pull sigven/pcgr:0.6.2.1`), and let me know if that works better.

best,
Sigve

**Comment by vladsaveliev** [comment]
Fantastic, that works now! Thanks Sigve.

**Comment by vladsaveliev** [comment]
Would you mind to also push the changes into GitHub? On our cluster, we use a modified PCGR runner that works without Docker, and would love to pull the new changes from git. By the way, if you are interested, this is the modified codebase: https://github.com/vladsaveliev/pcgr Basically it just runs tools locally, if started with `--no-docker` option. If you find it useful, I'd love to create a pull request. The reason we have it is that we can't have Docker on our HPC, unfortunately.

**Comment by zacshi** [comment]
Thanks so much for the no-docker option, we're in a similar situation.
