### ISSUE TITLE
gene fusion feature request.

### ISSUE THREAD

**Issue by plsysu** [sigven/pcgr#36]
Hi, Sigven, Now PCGR can analysis SNV/INDEl and CNA. would you like to add gene fusion function in the future?

Another question is that given tumor/normal raw data(fastq), can you recommend some pipeline to generate accurate variant file(vcf) ? The vcf looks like pcgr's examples, has multiple variant caller info.
This info can display on the HTML report.

thanks !

**Comment by sigven** [comment]
Dear Peng,
Thanks for your question, very relevant. The answer is yes, I want to have functionality for this :-) There are, as you probably are aware of, a number of biomarkers in the [CIViC database](https://civicdb.org/) that are linked to gene fusions, and which PCGR is currently not able to support. I am afraid I cannot provide any timeline as to when this can be offered, as one needs to figure out how the input should be defined, whether one should include any quality annotations pr. fusion etc. (I have little experience in this particular field, i.e. fusion detection in cancer). If you have any ideas, these are very welcome.

Regarding your other question, choice of somatic variant detection pipeline, there are a number of options available. In general, making a consensus set from multiple calling algorithms have proven to be strategy that can minimize the impact of false positive calls. In this regard, the pipelines provided by [bcbio](https://github.com/bcbio/bcbio-nextgen) is very solid, a number of PCGR users are using these.

**Comment by Sidra-TBI-FCO** [comment]
Maybe some inspiration can be found here: https://github.com/nf-core/rnafusion
