### ISSUE TITLE
CIViC source and version difference

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#40]
Hey Sigve,

Could you please point to how do you prepare or where do you download the CIViC vcf files for the PCGR bundles? I'm trying to understand why both these upstream TERT annotations from here https://civicdb.org/events/genes/79/summary/variants/248/summary/evidence/1646/summary#evidence were present in the PCGR bundle CIViC of April 16th 2018, but missing in the May 8th 2018 version. Even though the annotations it seems were not edited on the website for the past 2 years

Vlad

**Comment by sigven** [comment]
Hi Vlad,

I have not made the code for preparation of CIViC VCF public yet; it's basically a huge script that
combines the following two sets of variants in one big VCF:

1) variants unambiguously mapped to the genome (with ref and alt allele) by CIViC curators (GRCh37)
2) protein-coding variants not satisfying the criteria in 1) are mapped to the genomic variants through the use of [transvar](https://github.com/zwdzwd/transvar)

The combined set of 1) + 2) is ultimately mapped to GRCh38 with [crossmap](http://crossmap.sourceforge.net/)

To be frank, I have not a clear idea of why the TERT promoter variant got lost during the April/May update. It is present in my working CIViC dataset (not yet released with PCGR), so it will be taken care of shortly. Sorry for this.

regards,
Sigve
