### ISSUE TITLE
Regional hypermutation (Kataegis) request

### ISSUE THREAD

**Issue by hongiiv** [sigven/pcgr#41]
Hi, Sigven, PCGR can analysis MSI and mutational signatures. Would you like to add Kataegis in the future?

You can see the Kataegis from mutalisk (http://mutalisk.org). 

thanks!

**Comment by sigven** [comment]
Dear Changbum,

Great suggestion! I'd be happy to add functionality to indicate evidence of kataegis. Having looked at mutalisk.org, it seems the underlying software is not available for download(?), only available through the web, which makes it challenging for integration in PCGR. Correct me if i am wrong here. 

If you are aware of similar tools (stand-alone packages available for download, i.e. R packages, Python programs etc.) intended for kataegis analysis, that would be great.

regards,
Sigve

**Comment by ohofmann** [comment]
Sigve,

I tend to use [SeqKat](https://cran.r-project.org/package=SeqKat) for this, although similar approaches are also present in other frameworks.

**Comment by sigven** [comment]
Thanks Oliver, this looks much more convenient! I'll start making a testbed for this asap.

Sigve

**Comment by sigven** [comment]
Would any of you (@ohofmann or @hongiiv) have a test case that shows evidence of kataegis?

**Comment by ohofmann** [comment]
I don't think I can share the sample that I have in mind but happy to run any (beta) versions you want me to explore and report back?

**Comment by hongiiv** [comment]
mutalisk have a demo vcfs for melanoma and lung cancer.
You can check http://mutalisk.org/analyze.php

**Comment by Benja1972** [comment]
Here my attempt to recreate it in Python
https://github.com/Benja1972/bioinformatics/blob/master/Kataegis.py

**Comment by sigven** [comment]
Kataegis detection is now part of the workflow (when you include mutational signature analysis in your report , option --estimate_signatures)
