### ISSUE TITLE
Download data bundle slowly

### ISSUE THREAD

**Issue by qindan2008** [sigven/pcgr#42]
Hi Sigven,

When I downloaded data bundle from the link provided in STEP 2, the wire speed was too slow and frequently broken. I tried many times but all my attempt failed.
Can you shared me a download link which can be faster?

Thank you very much!

**Comment by sigven** [comment]
Hi,

I am afraid I have little control over this, and I suspect the bottleneck may be on your side (and not wrt. the Google Driver server that hosts the bundle)? I just tried the same download and experienced no problem. I would recommend that you first check whether there could be any problems with your local connection, before I start hosting the bundle in multiple servers.

regards,
Sigve
