### ISSUE TITLE
How to specify  a TOML configure  file

### ISSUE THREAD

**Issue by xiucz** [sigven/pcgr#43]
Hi,

I follow your no-docker to run the demo data, however, the log file shows that  the TOML doesn't exist in the default database dir PATH:
```
Default PCGR configuration file ~/Work/public_data/medicine/pcgr_data/data/grch37/pcgr_configuration_somatic_default.toml does not exist - exiting
``` 

 And my commands are as below:
```
PCGR_dir=~/Work/public_data/medicine/pcgr_data
OUT_dir=tmp_out

~/software/Anaconda3/envs/biosoft/bin/python \
~/PCGR/pcgr/pcgr.py \
--input_vcf ~/PCGR/pcgr/examples/tumor_sample.BRCA.vcf.gz \
$PCGR_dir $OUT_dir grch37 \
~/PCGR/pcgr/examples/pcgr_conf.COAD.toml \
tumor_sample.BACA --no-docker
```
 Thanks for your promoting advice.

**Comment by sigven** [comment]
Hi @xiucz,

Thanks for testing this! The no-docker option is still somewhat experimental, but Vlad Saveliev (@vladsaveliev) has done a terrific job so far with setting things up. Regarding your errors, I have a couple of comments, one specifically for Vlad:

- Have you checked that ~/Work/public_data/medicine/pcgr_data/data/grch37/pcgr_configuration_somatic_default.toml points to a valid file?
-  [EBI/vcf-validator](https://github.com/EBIvariation/vcf-validator/releases) needs to be run with version 0.6, it seems you use 0.7 (I played with the latest versions this summer, but things worked much easier with 0.6)

regards,
Sigve

**Comment by xiucz** [comment]
@sigven @vladsaveliev 
thank your replies! Both TOML files exist. I looked through the related issues with no-docker option and found vladsaveliev's great contribution. So it seemed there is no error during my installation(I have downloaded the database). 

I think validator with v0.6 may work well,  I will try to specify my validator to v0.6 in this conda environment.

And I suggest  to specify all the  dependent packages in  install_no_docker/conda_environment.yml to special version, eg. **r-ggplot2=2.2.0**. Is this make sense?

Another suggestion，for TOML file, we can use special variable than positional parameter, eg. 
**--toml example.toml**.

**Comment by xiucz** [comment]
Everything goes well now, I close it. Thank you.

**Comment by vladsaveliev** [comment]
Glad it worked!

> And I suggest to specify all the dependent packages in install_no_docker/conda_environment.yml to special version, eg. r-ggplot2=2.2.0. Is this make sense?

Absolutely agree about that! I only recently ran into this article https://nvie.com/posts/pin-your-packages/ explaining why you should pin all dependencies for end products (vs libraries). I'm planning to freeze all dependency versions, which will hopefully make the no-docker option almost as reliable as the virtualized one.
