### ISSUE TITLE
Dockerize entire app?

### ISSUE THREAD

**Issue by DavidAustinNix** [sigven/pcgr#46]
Hello Folks,

It would help considerably to dockerize the entire toolkit.  This would allow us to run it using udocker in our protected domain linux cluster were root access is not allowed.  As it is,  docker calls from the pcgr.py effectively requires root.  This is OK in our dev environment but not in production.

Thanks, David

**Comment by sigven** [comment]
Hi,
You raise a valid point. Seen this contribution by @vladsaveliev?
https://github.com/sigven/pcgr/blob/master/install_no_docker/README.md
Might be another option for you.

Best,
Sigve

**Comment by DavidAustinNix** [comment]
Yes, this will likely collide with our existing python installations. 

That said, it wouldn’t be horrendous to do this no docker install in a docker image.  And then in our protected environment use udocker to run it.

Thanks for the link.

-cheers, David

**Comment by vladsaveliev** [comment]
Hi David,

The no-docker approach creates an isolated conda environment, so it shouldn't hopefully collide with system pythons.

Vlad
