### ISSUE TITLE
problematic CNA file

### ISSUE THREAD

**Issue by przemekl** [sigven/pcgr#47]
I have problem with attached file 
[04TL_clean.called.txt.gz](https://github.com/sigven/pcgr/files/2456916/04TL_clean.called.txt.gz) 
with copy number aberrations.
Without it, the analysis proceeds seamlessly.
When I include file, the following messages appear:
[INFO] Assigning elements to PCGR value boxes
Quitting from lines 4-7 (./value_boxes.Rmd) 
Quitting from lines NA-7 (./value_boxes.Rmd) 
Error in data.frame(x = rep(seq(2, 15, 6.5), 2), y = c(rep(2, 3), rep(6.5,  : 
  arguments imply differing number of rows: 6, 7
Calls: <Anonymous> ... withVisible -> eval -> eval -> <Anonymous> -> data.frame
Execution halted.

**Comment by sigven** [comment]
Hi, thanks for reporting! Debugging now. Quick question: is your CNA coordinates mapping to grch37 or grch38?

**Comment by przemekl** [comment]
GRCh38
PCGR version 0.6.2.1

**Comment by przemekl** [comment]
The same error still appears, the last line is slightly different
Calls: <Anonymous> ... withVisible -> eval -> eval -> <Anonymous> -> data.frame

**Comment by sigven** [comment]
Hm, ok. Could you share the config file you are using as well? And do you feed in any VCF at the same time, or do you only annotate the CNA file?

**Comment by przemekl** [comment]
I am trying to process both files.
Config file: 
[pcgr_to_check.toml.gz](https://github.com/sigven/pcgr/files/2463762/pcgr_to_check.toml.gz)

Vcf with one variant (one line is enough):
[04TL_biallelic_for_pcgr.vcf.gz](https://github.com/sigven/pcgr/files/2463766/04TL_biallelic_for_pcgr.vcf.gz)

It is interesting that each of these files processed separately does not cause problems

**Comment by sigven** [comment]
Hi,

I found the bug, very stupid paste error in R when multiple CNA's were found as clinically actionable (for display in value boxes). Reason it worked when you analyzed the CNA without the VCF is that the value boxes are omitted in this case. Here are links to your reports, FYI:

https://www.dropbox.com/sh/2jwgey2sxqfk344/AABpGDJ7CFcuW0g2GokzwnQNa?dl=0

Should work properly with sigven/pcgr:dev now.

Thanks a lot for reporting!

regards,
Sigve
