### ISSUE TITLE
Difference of variants in vcf and json

### ISSUE THREAD

**Issue by angsm** [sigven/pcgr#50]
Hi,
I really appreciate the usability and functions in this tool. 
But I think I need some clarification on how the tier-ed json file is produced. We realized that the number of variants in the vcf file does not match the number of variants in the json file, we just need to note down the reason why. (Currently using version 0.6.2.1)

Thank you
Shimin

**Comment by sigven** [comment]
Hi Shimin,

Thanks for your message. Could you give me your example VCF, so I could have a closer look at it? There are some potential reasons why the numbers do  not match, but if all variants in your VCF are 'PASS' and they all map to the ordinary chromosomes, they numbers should in principle correspond. If you upload your example VCF, I can have a closer look and see if there is something PCGR is missing.

regards,
Sigve

**Comment by angsm** [comment]
Hi Sigve,

Let me check if I can send you a vcf file.

Apologies for the late reply.

**Comment by angsm** [comment]
Attached is the [https://dl.dnanex.us/F/D/xgbxvZvzBx58X1pBZ8519j68f5Kz7qxf71g00Vg4/sample.vcf](vcf) file with only position "47641505" and "48030639" appearing in the tiered json file. The variants in the vcf file are all 'PASS', at first I thought that it could be due to them being multiallelic, but its not.

**Comment by sigven** [comment]
Hi Shimin,
Can you try with the [dev version](https://github.com/sigven/pcgr#development-version)? Tested your VCF with dev just now, results can be found here:
https://www.dropbox.com/sh/ptcf4nintparlk3/AACZBac89d6LrkwPZaeiBEB_a?dl=0

regards,
Sigve

**Comment by sigven** [comment]
Closing the issue for now, re-try the latest dev version if you like.

**Comment by angsm** [comment]
Hi Sigven,

Sorry for the late reply as it has been very hectic. As per your last post, we have been running with the dev version, everything was good, most of the variants missing in the json file were "NONCODING".

But we found that a particular position, **66766356** was not tiered into the json file. the sample vcfs can be found below:

https://dl.dnanex.us/F/D/05546qZxBK9F4jx8fkk3VfJKKf4PJQ324Kbp403g/S1.vcf https://dl.dnanex.us/F/D/6J8P0Y4QgzYbZpk7Xzzjp8ZY8QFYbXZV8Xbv0f42/S2.vcf


Thank you
Shimin
