### ISSUE TITLE
maf2vcf does not report t_depth t_ref_count	t_alt_count	n_depth	n_ref_count	n_alt_count

### ISSUE THREAD

**Issue by apastore** [sigven/pcgr#52]
Hi Sigven,
Thanks  a lot for implementing vcf2maf in pcgr. 
I see that maf2vcf does not include 
t_depth | t_ref_count | t_alt_count | n_depth | n_ref_count | n_alt_count
aslo the tumor_samples barcode does not report the sample ID. 
Aslo would be nice to add the annotation from PCGR (like mutation TIER ) 

Thanks a lot!
Alessandro

**Comment by sigven** [comment]
Hi Alessandro,

Thanks for your message. In order to populate the MAF with this info, i need to add a step at the final stage of the workflow, since not everything can be extracted from the VCF by vcf2maf. I'll add this on the enhancements list.

thanks,
Sigve

**Comment by sigven** [comment]
When allelic fraction and sequencing depth (tumor, control) is properly defined, this information will be appended to the MAF output (PCGR v0.8.2)
