### ISSUE TITLE
Error: Could not write to FASTA lock file (Grch38)

### ISSUE THREAD

**Issue by jo6fu3** [sigven/pcgr#54]
Hi Sigve,

I meet an error when I running pcgr in no_docker mode with grch38 reference version.

> MSG: ERROR: Could not write to FASTA lock file /pkg/biology/PCGR/PCGR_v0.6.2.1/data/grch38/.vep/homo_sapiens/94_GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.vep.lock
![image](https://user-images.githubusercontent.com/8158587/47632638-eaba2080-db85-11e8-86dc-3a275d544e64.png)

But I didn't meet this error when running pcgr with grch37 reference version.
Could you please help me to fix it?
Thanks!

Weichi

**Comment by sigven** [comment]
Hi Weichi,

Thanks for your message. I am pretty sure this is an installation error. Have you tried removing the bundle and re-download? (cc @vladsaveliev)

Sigve

**Comment by jo6fu3** [comment]
Hi Sigve,
We fixed the error by re-download and add the read permission.
Thanks.
