### ISSUE TITLE
Number of variants used to determine MSI status

### ISSUE THREAD

**Issue by przemekl** [sigven/pcgr#55]
What could mean a statement "The number of SNV/InDel calls (n = 3296) is too limited (n < 30) for MSI prediction to be performed."?

**Comment by sigven** [comment]
Hi,
That clearly is misleading (I will correct this). 

I do know that the MSI prediction algorithm is relying on coding variants only (since this is what the model is trained with from TCGA data). 

Have you checked how many SNVs/InDels are found as coding variants in your query?

best, 
Sigve

**Comment by przemekl** [comment]
Now it's clear. I have only 21 coding variants. Please close the issue.

**Comment by sigven** [comment]
Thanks, I am pushing the fix shortly, so you should get the correct error message.

Sigve
