### ISSUE TITLE
VEP plugins

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#56]
Sigve,

As far as I'm aware in order to apply VEP plugins, you need to specify them in `vep` command line, i.e.:

```
vep --input_file .... --plugin miRNA --plugin LoF
```

[See:](https://github.com/konradjk/loftee#usage)

> Basic usage:
> `perl variant_effect_predictor.pl [--other options to VEP] --plugin LoF`

[and:](https://github.com/Ensembl/VEP_plugins)

> ...for most you will just need to put the module in your ~/.vep/Plugins directory (or elsewhere on your $PERL5LIB) and then run the VEP with the argument --plugin <module name>.

I can't find if you define them this way: https://github.com/sigven/pcgr/blob/master/pcgr.py#L493-L497. You don't use them or there is another way to apply plugins that I'm missing?

**Comment by sigven** [comment]
Vlad,

Take a look at the [cpsr.py script](https://github.com/sigven/cpsr/blob/master/cpsr.py) in the cspr repo. It uses the LoF plugin (still not using the microRNA annotation plugin, it is there for potential future use). Reason  am not applying the LoF plugin in the PCGR workflow is that I have experienced that it may induce a signifcant larger run time for VEP (I have asked the loftee plugin author whether this is expected, but not recieved any answer), and it's use is primarily needed in the CPSR workflow. 

Regarding the actual installation, I must admit I found this somewhat confusing and challenging. I made it working through the application of some custom changes. Basically, I add the compressed archive with the [loftee code base and data](https://github.com/sigven/pcgr/blob/master/src/loftee.tgz) to make it work. If you have a more elegant solution, let me know.

Sigve

**Comment by vladsaveliev** [comment]
Got you. 

Interesting, in our projects, the number of germline mutations is really big (we do WGS), but somatic numbers are rather low (we do tumor/normal with pretty pure tumors).

I think I figured how to install loftee nicely with no-docker solution. `conda install ensembl-vep` installs the plugins automatically, and I just need to add it to the vep command line: `--plugin LoF,loftee_path:$CONDA_PREFIX/pcgr/share/ensembl-vep-94.4-0 --dir_plugins $CONDA_PREFIX/pcgr/share/ensembl-vep-94.4-0`. It should also work with standard VEP installation (i.e. within Docker) if you clone and copy the loftee repo somewhere and replace `$CONDA_PREFIX/pcgr/share/ensembl-vep-94.4-0` with this location. Will test more and make a pull request for no-docker for now.

Vlad
