### ISSUE TITLE
Some feature request

### ISSUE THREAD

**Issue by patidarr** [sigven/pcgr#58]
Hi,

we have certain markers we were hoping you could include into the report on some in the main results :) 

For example:
Tiering variants based on oncoKB
%LOH. I can provide this as command line input and if that can appear as a box, it would be very helpful
MSI score/status, I found the mSINGS score to be more accurate and was thinking to use that instead, again as a command line input.
Tumor Purity and cellularity.

Thanks,
@patidarr

**Comment by sigven** [comment]
Hi @patidarr,

Thanks for your suggestions. Regarding oncoKB, there are issues regarding licensing which prohibits me to include it as a resource in an open-source effort:
[https://github.com/oncokb/oncokb-public/issues/95](https://github.com/oncokb/oncokb-public/issues/95)

I agree that purity, LOH and cellularity would be beneficial to include, and we are working on adding markers such as this to the report. Possibility to include gene expression data will also be prioritized, enabling reports for existing gene expression biomarkers for prognosis and drug sensitivity etc.

regards,
Sigve
