### ISSUE TITLE
Inconsistent exclusion of germline variants

### ISSUE THREAD

**Issue by przemekl** [sigven/pcgr#60]
For testing purposes I set all maf_onekg_* and maf_gnomad_* options to 1 and exclude_dbsnp_nonclinical to false.
It turned out that total number of variants remaining after excluding coinciding germline variants did not equals the initial variants number.
I found an example variant, excluded after gnomAD processing - chr13:32316435 G/A (rs1799943,hg38)

**Comment by sigven** [comment]
Thanks, realized that one option is missing from the given PCGR toml file (*maf_gnomad_asj*), I believe that is causing the problem. Updated TOML file is pushed now.

**Comment by przemekl** [comment]
If the same problem does not appear for 1k genomes project populations? The number of variants differs also for this processing stage.

**Comment by sigven** [comment]
You are correct. I'll dig some more into the issue:-)

**Comment by sigven** [comment]
Pushed now in *dev*, replaced a` < `operator with a `<=` operator. That should keep also variants with 1000 Genomes AF = 1.
