### ISSUE TITLE
Submitting gene names for copy number

### ISSUE THREAD

**Issue by pramaraom** [sigven/pcgr#72]
Hi Sigven,

Thank you for a great package. I was wondering if it was possible for the CNA alterations to submit just the gene names instead of the chromosome positions? This is because I want to include some structural variants that are completely disrupted and submit them as "deletions". Is there a way to do this?

Thank you,
Priya

**Comment by sigven** [comment]
Dear Priya,
Thanks for your message, and apologies for the late response. I can see your needs, but at this point PCGR do not have the flexibility to accept this type of input. A distinct structural variant input (in addition to the somatic CNA input) would probably be a future solution to deal with this.

best,
Sigve
