### ISSUE TITLE
New line carriage for Tier 2 variants in report

### ISSUE THREAD

**Issue by ridwan-shaikh** [sigven/pcgr#73]
Hi,

Thank for an amazing package. Just thought I would let you know of a small error in line 110 of value_boxes.R:

pcg_report_value_box[['tier2']] <- paste0('Tier 2 variants:0\n')

I believe the new carriage line should be before the 0: ('Tier 2 variants:\n0')

**Comment by sigven** [comment]
Hi,

Thanks a lot! Will fix. FYI: Additional updates coming shortly (clinicaltrials info, more reference data from TCGA) ++

**Comment by ridwan-shaikh** [comment]
Thanks Sigven. Can’t wait for the new features!
