### ISSUE TITLE
Extracting AF from sample specific coloumns

### ISSUE THREAD

**Issue by sahilseth** [sigven/pcgr#74]
Is it possible to specify the `name` of the tumor sample in the VCF, and then for pcgr to extract `AF`, `DP` from that column?

Do you a recommended approach, to extract AF from sample specific columns and add them to the INFO field of the VCF?

Thanks for the great tool!

**Comment by sigven** [comment]
Hi,

Thanks for reporting. This is very relevant question, and related to a [previously reported issue](https://github.com/sigven/pcgr/issues/22). Ideally, PCGR should interpret any VCF coming from any variant caller (I acknowledge that e.g. mutect2 is by far one of the most common somatic callers), and automatically fetch the depth and allelic fraction for the tumor and control sample. After several years of dealing with VCF files from a multitude of variant callers, I must admit that dealing with this in a robust way is in fact quite a huge undertaking, and is something I have not been able to prioritize yet. Therefore this burden is currently put on the users to manage themselves. I fully realize that many would like PCGR to handle this on the inside, but as mentioned, I have not had the capacity to prioritize this part.

If you can contribute anything to the community by yourself here (e.g. a 'prepare_pcgr_vcf.py' script that accepts a mutect2 vcf, retrieves DP/AF of specified tumor and control sample from the SAMPLE columns and appends this to the INFO colum), that would be warmly welcomed.

kind regards,
Sigve
