### ISSUE TITLE
grch38 vs grch37 misannotation?

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#79]
Hi Sigve, 

I ran into this variant that is prioritized differently in GRCh37 and GRCh38. It's 11:31815582 G>C in GRCh37, and 11:31794034 G>C in GRCh38 ([see PCGR intermediate/output files attached](https://github.com/sigven/pcgr/files/3353598/grch37_grch38_PAX6.zip)). VEP annotations are pretty similar for both builds: it's a missense mutation in PAX6 splice site, and it also have a secondary annotation as a ELP4 downstream_gene_variant. GRCh37 one prioritizes it as a TIER3 PAX6 variant as I would expect, however for some reason GRCh38 run reports it as ELP4 variant in the NONCODING tier. Just wondering if I'm misunderstanding anything. Would expect it to be PAX6 tier 3 for in GRCh38 as well.

Vlad

**Comment by sigven** [comment]
Hi Vlad,
Thanks for the notification! Your expectations seem right, should not be any different classification for different builds. I'll have a closer look of what's going on.

**Comment by vladsaveliev** [comment]
Looks like the difference is because of a custom VEP's pick order option: I selected APPRIS to be the first in order to pick the transcript. 

The best PAX6 transcript is annotated as PRINCIPAL:4 in APPRIS ("Where the APPRIS core modules are unable to choose a clear principal CDS and there is more than one variant with a distinct (but consecutive) CCDS identifiers, APPRIS selects the longest CCDS isoform as the principal variant."

The best ELP4 transcript is however PRINCIPAL:3 ("Where the APPRIS core modules are unable to choose a clear principal variant and there more than one of the variants have distinct CCDS identifiers, APPRIS selects the variant with lowest CCDS identifier as the principal variant. The lower the CCDS identifier, the earlier it was annotated.")

So I moved biotype in the beginning and using `--pick_order biotype,appris,ccds,rank,tsl,length,canonical` now, it fixes the issue!

**Comment by sigven** [comment]
Ah thanks for looking more closely into it! I am in the process of upgrading to VEP 97, and thought to have it assessed there. This version comes with yet another criterion for picking the primary transcript, MANE:
https://devyser.com/articles/simplify-gene-transcript-selection/

Pretty tricky to get the "correct" primary transcript all the time it seems, but fiddling with the pick-order should at least be worthwhile.

best,
Sigve

**Comment by vladsaveliev** [comment]
Oh, MANE project is great, they harmonize RefSeq and Ensembl annotations. Would be good to explore.

**Comment by vladsaveliev** [comment]
After changing the pick order to have canonical first, it does pick a PAX6 transcript, but it's not the best one: it's really just the longest one with TSL=5 ("no single transcript supports the model structure"): http://asia.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000007372;r=11:31784779-31817961

So I'm hesitant to keep canonical first just to resolve multiple genes annotations. I think it worked just of luck and might fail with other genes, when an unsuitable gene will turn out to be the longest.

Wondering if it's possible to report variants in different genes separately in PCGR? So basically, just split the variant into 2 VCF records if there are 2 different gene annotations.

**Comment by vladsaveliev** [comment]
Perhaps different pick options like `--per_gene` and `--pick_allele_gene` will help? https://asia.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick_options

**Comment by vladsaveliev** [comment]
Right, can use `--flag_pick_allele_gene` instead of `--flag_pick_allele`, and then split in parse_vep_csq function. Even just using `--flag_pick_allele_gene` solves the problem for this case, because PAX6 goes first in the list.

**Comment by vladsaveliev** [comment]
After exploring more putting the consequence (`rank`) first in order seems to be the best option short term:` --pick_order rank,appris,biotype,ccds,tsl,length,canonical`. Though it would be nice to split by gene and have a separate record in the report for each gene if the variant affects multiple genes.

**Comment by sigven** [comment]
I am actually using `--flag_pick_allele_gene` in the VEP processing of CPSR, but cannot seem to recall why it is not used in PCGR. Minor thing either way I believe to incorporate it into PCGR.

**Comment by sigven** [comment]
There is the VEP_ALL_CSQ variable appended for every record in order to capture all possible transcript consequences (also for other genes), but I may append a more visible flag to say that a particular variant affects different genes. Splitting a single variant into multiple records may be somewhat confusing to people, and have quite some implications for how to report the variant statistics etc.

**Comment by vladsaveliev** [comment]
Makes sense. Agree that it would be confusing. I think just picking `rank` first will solve the problem for most of such cases, and if you add a flag warning about multiple genes, it will be a helpful for the cases if VEP still didn't chose the right gene. 

Regarding `--flag_pick_allele_gene`, it makes VEP set the PICK flag for multiple annotations (so each gene has one PICK flag). With the current PCGR implementation, it will just choose the first gene in the list (here https://github.com/sigven/pcgr/blob/078b51c45fe2a86bedfe3ca8861913cb05d70fd4/src/pcgr/pcgr_summarise.py#L99-L108), which is not good perhaps. That would have been helpful if we split annotations per gene as I suggested earlier, but I guess no need to change that now.

**Comment by sigven** [comment]
Yeah, see that now. Code assumes a single record for PCGR (`--flag_pick_allele`). Recognise some room for improvements to the code comments.. :)

I think moving the `rank` to the front as you suggest seems like a reasonable strategy, so will change the default order i the config to reflect that.

S
