### ISSUE TITLE
annotated VCF

### ISSUE THREAD

**Issue by foxchase** [sigven/pcgr#8]
Hi Sigve,
PCGR works on the unannotated VCF files. How can I convert the annotated VCF to unannotated VCF to fit your PCGR?

**Comment by sigven** [comment]
Hi,
The simplest solution: do not annotate the query VCF prior to annotation with PCGR. As stated in the documentation (http://pcgr.readthedocs.io/en/latest/output.html), the workflow requires an unannotated VCF, coming directly from variant calling. It is unlikely that VCF annotations from variant calling coincide with PCGR's functional annotations.
