### ISSUE TITLE
ensemble-vep version in the conda environment

### ISSUE THREAD

**Issue by mtandon09** [sigven/pcgr#80]
Hello,
  I was trying to install and run the "condarized" version, and kept getting errors during the VEP annotation step. I eventually traced the error to a version mismatch between the VEP data provided in the bundle (96) and what conda installed (97).

I think this is arising from the fact that the `meta.yaml` (found at `pcgr/install_no_docker/conda_pkg/pcgr/meta.yaml`) is asking for `ensembl-vep>=94` on Line 91.  Looks like there was a new release of VEP recently, so conda installed the latest one.  It might be better to fix the version requested to 96 until you all update the bundle to make the install process more seamless.

Just wanted to throw it out there.  Thank you for a beautiful reporting tool!

**Comment by sigven** [comment]
Hi,
And thanks a lot for notifying this issue! I’ll have a look.

Best, 
Sigve

**Comment by sigven** [comment]
Dear Vlad (@vladsaveliev),
Would you care to have a look at this? 

best,
Sigve

**Comment by vladsaveliev** [comment]
Sorry, didn't notice this. Sigve, thanks for pinging me.

@mtandon09, that's exactly right, we should be pinning VEP to the version used in the data bundle. Created a PR with the fix now. Conda packages should be rebuilt soon.

Vlad

**Comment by sigven** [comment]
Thanks for your assistance, @vladsaveliev, and your bug report @mtandon09.
