### ISSUE TITLE
Star allele and CPIC guidlines

### ISSUE THREAD

**Issue by kokyriakidis** [sigven/pcgr#81]
Do you have in mind including Star allele pipeline and CPIC guidlines?

**Comment by sigven** [comment]
Hi,
Thanks for your suggestion. Could you include a pointer/URL for what this refers to?

**Comment by kokyriakidis** [comment]
This is an implementation from PharmGKB that uses CPIC guidelines and suggests dosage changes on drugs that are affected by different alleles by their metabolized genes. This is so cool because  of the report it generates!
```
http://pharmcat.org/
```

There are other implementations (maybe better ones) but do not produce a nice visual output.
```
https://stargazer.gs.washington.edu/stargazerweb/
```

So I thought you could work on that because I really like your reports :)

**Comment by sigven** [comment]
Dear @kokyriakidis,

Thanks a lot for your input, highly appreciated. And sorry for the truly late response. First, regarding the CPIC guidelines. Clearly, this is a relevant and exciting topic, and from looking at the [PharmCAT](https://github.com/PharmGKB/PharmCAT) project, that tool looks really promising. Although these guidelines and implementations clearly is at the core of genomic medicine, I am not convinced that an implementation of these guidelines is within the scope of PCGR (at least how it has been designed currently). Keep in mind that PCGR is intended for the analysis and prioritisation of clinically relevant findings of acquired, somatic aberrations in a given tumor. The input for CPIC guidelines constitute germline variants from a given case/patient, which is not currently considered for interpretation by PCGR. The other tool in development, the [Cancer Predisposition Sequencing Reporter, CPSR](https://github.com/sigven/cpsr) is focusing on the germline, but largely related to the analysis of cancer susceptibility alleles, and not currently dealing with pharmacogenomics aspects.

With respect to targeted drugs in PCGR reports, there are a number of aspects related to this. Without going too much into details, PCGR is primarily integrating knowledge on targeted cancer drugs (and associated drug sensitivity markers) from two sources: [targetvalidation.org](https://targetvalidation.org), and [CIViC](https://civicdb.org). The reason that there were only two genes that are targetable is that are are no cancer drugs (at late stage in clinical development) that are targeted towards the other gene amplifications present in the given case. You can browse the different drugs that are targeted towards ERBB2 here (in the context of breast cancer):

https://www.targetvalidation.org/evidence/ENSG00000141736/EFO_0000305?view=sec:known_drug

Hopefully this was somewhat helpful,

thanks again for your interest, closing this for now.
Sigve
