### ISSUE TITLE
Step4 erro

### ISSUE THREAD

**Issue by xiaoqiwang19** [sigven/pcgr#83]
Hi Sigve,
Please guide me, since I am getting below error:
docker run --rm -t -u 0 -v=/DATA/geyunxia/software/PCGR/pcgr.v0.7.0/pcgr-0.7.0:/data -v=/DATA/geyunxia/software/PCGR/pcgr.v0.7.0/pcgr-0.7.0/data/grch37/.vep:/usr/local/share/vep/data -v=/DATA/wangxiaoqi/wct_cfDNA/pcgr/20180813/WP10002664:/workdir/input_vcf -v=/DATA/geyunxia/software/PCGR/develep_version/pcgr:/workdir/input_conf -v=/DATA/wangxiaoqi/wct_cfDNA/pcgr/20180813/WP10002664:/workdir/output -w=/workdir/output -e TMP='/workdir/output' sigven/pcgr:0.7.0 sh -c "/pcgr.R /workdir/output /workdir/output/WP10002664.pcgr_acmg.grch37.pass.tsv.gz None WP10002664 /workdir/input_conf/pcgr.tumoronly.toml 0.7.0 grch37 /data"
.....

2019-08-13 16:29:05 [INFO] Generating tiered set of result variants for output in tab-separated values (TSV) file
2019-08-13 16:29:30 [INFO] ------
2019-08-13 16:29:36 [INFO] ------
2019-08-13 16:29:36 [INFO] Assigning elements to PCGR value boxes
2019-08-13 16:29:36 [INFO] ------
2019-08-13 16:29:36 [INFO] Writing JSON file with report contents
Error in collapse_object(objnames, tmp, indent) : 
  R character strings are limited to 2^31-1 bytes
Calls: <Anonymous> ... vapply -> FUN -> FUN -> .local -> collapse_object -> .Call
Execution halted

**Comment by sigven** [comment]
Dear @xiaoqiwang19,
Thanks for your report. I noticed that you are using an old version of PCGR (0.7.0). Would you care to repeat your run with the latest release and see if the error still remains?

best,
Sigve

**Comment by sigven** [comment]
Closing this issue for now.
