### ISSUE TITLE
Preparing vcf and tsv files

### ISSUE THREAD

**Issue by ersankose** [sigven/pcgr#86]
How can acquire these fields in vcf?
TCGA_CODE=COAD;
TVAF=0.xxxxxxxxx;
TDP=21;
TAL=muse,mutect2,somaticsniper,varscan2

And COAD.cna.tsv head includes additional Num_Probes | Segment_Mean fields. How can i prepare tsv and vcf fields for pcgr?

Thanks.

**Comment by sigven** [comment]
Dear @ersankose,
If I understand you correctly you are wondering how to prepare your input files (VCF, copy number segments) for PCGR. Essentially, you need to look at how these aberrations are formatted in your variant calling pipeline and then try to pull out the information that is required for PCGR analysis, and for some of the properties provide them in the configuration file. In the situation for VCF (SNVs/InDels), there are sadly no standards for reporting different properties of somatic variants (depth, support for alternate allele etc), so PCGR requires that you provide how this is formatted in your query VCF in the [configuration file](https://pcgr.readthedocs.io/en/latest/input.html#pcgr-configuration-file). You may have to reformat the VCF file slightly to fit with PCGR requirements. Do however note that PCGR may process your data, although suboptimal, without providing any information with respect to variant depth and allelic support. If these parameters are provided correctly, the report contents would be displayed optimally.

Similarly for copy number aberrations, take a look at how your variants are reported from the calling procedure, and transform them to the requirements for PCGR (note that 'Num_Probes') is not a required field, see [requirements here](https://pcgr.readthedocs.io/en/latest/input.html#copy-number-segments).

Hope this may help somewhat.

best,
Sigve
