### ISSUE TITLE
Pre PCGR workflow

### ISSUE THREAD

**Issue by ersankose** [sigven/pcgr#88]
Is there any "prepare_pcgr_vcf.py" from fastq to VCF for PCR ?

**Comment by sigven** [comment]
Dear @ersankose,
This is beyond the scope for PCGR. Please note that PCGR is intended for annotation and interpretation of a variant set, and not the variant calling per se. PCGR is considering the typical output from a variant calling pipeline (i.e. from fastq to VCF) as its input. The numerous somatic variant calling pipelines that exist are usually fairly similar (some examples below), but they frequently use different combinations of variant detection algorithms (MuTect2, Strelka2, GATK4, SomaticSniper, VarScan2, Muse, Vardict etc etc). Most of them produce VCF files, which constitute the main input for PCGR.

- [sarek](https://github.com/SciLifeLab/Sarek)
- [gatk4-somatic-snvs-indels](https://github.com/gatk-workflows/gatk4-somatic-snvs-indels)
- [bcbio](https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#somatic-with-germline-variants)

regards,
Sigve
