### ISSUE TITLE
Analysis with panel data

### ISSUE THREAD

**Issue by kokyriakidis** [sigven/pcgr#89]
Hello @sigven ! 

I would like to calculate TMB using data generated from panels. Am I able to do so with this tool? Do I have to use a specific panel?

**Comment by sigven** [comment]
Dear @kokyriakidis,
Thanks for getting in touch:-) Calculation of TMB from panel data should be possible, but I reckon that for very small panels the TMB estimate would be quite unstable (I have not followed the literature closely in terms of the minimum size of the panel for a robust estimate, but I believe the minimum should be around 1 Mb). First you need to gather the size of your panel (in megabases). Based on this number, you need to configure one essential part in the PCGR configuration file (.toml), that is `target_size_mb` (currently set to exome size, approx 34 Mb). You may also try to configure your thresholds for TMB high (parameter `tmb_intermediate_limit` in configuration file) pending on the tumor type in question, considering [recently reported cancer-specific thresholds](https://ascopubs.org/doi/10.1200/PO.18.00400). Let me know how it works.

best,
Sigve

**Comment by hongiiv** [comment]
FYI,
WES is the gold standard to derive the TMB.
FDA approved TMB panels are
- FoundationOne CDx(F1CDx)panel (>300 genes)
- MSK-IMPACT panel (>400 genes)

according to [this paper](https://jitc.biomedcentral.com/articles/10.1186/s40425-019-0681-2) 
> currently available panels can accurately assess TMB only in several particular cancer types; and accuracy outperformed correlation in assessing the performance of panel-based TMB estimation. Accuracy and cancer type individualization should be incorporated in designing panels for TMB estimation.

**Comment by sigven** [comment]
Thanks for valuable input, @hongiiv. I believe this corresponds well with my impression that one needs [at least 1Mb of targeted, coding region](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5395719/) to assess TMB robustly.
