### ISSUE TITLE
PCGR support for germline variants

### ISSUE THREAD

**Issue by tushardave26** [sigven/pcgr#90]
Hello @sigven 

Thank you for making `PCGR`.

I am just wondering that can I use `PCGR` for a `VCF` generated by `GATK4` germline workflow?

Best,
Tushar

**Comment by sigven** [comment]
Hi @tushardave26,

I have developed a different tool for the analysis of germline variants, with a focus on cancer predisposition: [Cancer Predisposition Sequencing Reporter](https://github.com/sigven/cpsr)

best,
Sigve
