### ISSUE TITLE
GRCh37 vs GRCh38

### ISSUE THREAD

**Issue by kokyriakidis** [sigven/pcgr#91]
Hi @sigven !

Could you explain why you and many other people use GRCh37 in your analysis instead of hg38? Are there some limitation in using hg38?

**Comment by sigven** [comment]
Hi @kokyriakidis,
Basically, a lot of people still have sequencing pipelines that produce output based on the GRCh37 assembly (my local institution included). There are not any limitation with hg38, if your variant datasets are hg38, stick to that. 

Best,
Sigve

**Comment by kokyriakidis** [comment]
And one more question. Why there are many conf files for each cancer type? They look pretty the same
