### ISSUE TITLE
OncoKB

### ISSUE THREAD

**Issue by kokyriakidis** [sigven/pcgr#92]
Hi @sigven !

I see many personalised cancer reports using the OncoKB database. Are you familiar with it?
```
http://oncokb.org/
```
You use all kind of databases but not this. Is there a reason?

You can also have a look in this:
```
https://iclusion.org/hmf/10299
```
and in this database
```
https://www.cancergenomeinterpreter.org/biomarkers
```
I found them in this report from Hartwig Medical Center in Netherlands
```
https://www.hartwigmedicalfoundation.nl/wp-content/uploads/2019/09/hmf_patient-report-example-aug2019.pdf
```

**Comment by sigven** [comment]
Hi,

There have been questions about OncoKB before, reason this is not included is licensing issues. PCGR is fully open-source. Take a look here:

[https://github.com/sigven/pcgr/issues/58](https://github.com/sigven/pcgr/issues/58)
[https://github.com/oncokb/oncokb-public/issues/95](https://github.com/oncokb/oncokb-public/issues/95)

BIomarkers from the Cancer Genome Interpreter is already included in PCGR, but not given much highlight any longer as this resource is not being actively maintained (last update January 2018).

thanks,
Sigve
