### ISSUE TITLE
can't download data bundles

### ISSUE THREAD

**Issue by guocaiyao** [sigven/pcgr#94]
thanks for your great tool, and now I'm in china, can't download data bundles. Is there other method to download data or other data warehouse to use? thanks for your reply!

**Comment by sigven** [comment]
Hi,Thanks for reaching out. I am working on an alternative host. Will keep you updated!

**Comment by brucemoran** [comment]
Any update? Looks like Google have stopped access by curl and wget methods...

**Comment by sigven** [comment]
Hi,

Thanks for the notification, and sorry for the late progress.

Try adding this as the baseline URL:
http://insilico.hpc.uio.no/pcgr/

grch38: http://insilico.hpc.uio.no/pcgr/pcgr.databundle.grch38.20191116.tgz
grch37: http://insilico.hpc.uio.no/pcgr/pcgr.databundle.grch37.20191116.tgz

I will try to keep this as an alternative host also in the future.

best,
Sigve

**Comment by brucemoran** [comment]
Thanks Sigve, 

BTW I'd be interested to see scripts that you have for generating data bundles, feel free to message me if you're interested in setting up some way of automating that if you haven't done so already.

Bruce.

**Comment by sigven** [comment]
Thanks for reaching out, Bruce. I have it somewhat semi-automated currently, but it would of course be convenient to have it even more automated. I'll get back to you.

best,
Sigve

**Comment by sigven** [comment]
Databundles now hosted on a dedicated server, not based on Google Drive.
