### ISSUE TITLE
Is it possible alternative sharing platform?

### ISSUE THREAD

**Issue by ngslabex** [sigven/pcgr#95]
Google Drive: Sorry, you can't view or download this file error
...
If too many users view or download a file, it may be locked for a 24 hour period before the quota is reset. The period that a file is locked may be shorter according to Google.
...

**Comment by sigven** [comment]
I realise that the Google solution is suboptimal. Others have also complained about this. I am in the process of making an alternative host for the data bundles. Putting this as an enhancement. Thanks for the notification!

**Comment by jxshi** [comment]
I have encountered the same issue recently.

**Comment by sigven** [comment]
Try adding this as the baseline URL:
http://insilico.hpc.uio.no/pcgr/

grch38: http://insilico.hpc.uio.no/pcgr/pcgr.databundle.grch38.20191116.tgz
grch37: http://insilico.hpc.uio.no/pcgr/pcgr.databundle.grch37.20191116.tgz

I will try to keep this as an alternative host also in the future.

**Comment by sigven** [comment]
Databundles are now (v0.9.0rc) hosted on a dedicated server, not Google Drive-based.
