### ISSUE TITLE
Execution halted

### ISSUE THREAD

**Issue by ersankose** [sigven/pcgr#96]
I have received error using pcgr-0.8.3 in Step 4;

..............
2019-11-20 03:06:12 [INFO] Assigning elements to PCGR value boxes
2019-11-20 03:06:12 [INFO] ------
2019-11-20 03:06:12 [INFO] Writing HTML file with report contents
Quitting from lines 121-149 (./acmg/tier2_acmg.Rmd) 
Quitting from lines NA-158 (./acmg/tier2_acmg.Rmd) 
Error in list(crosstalk::filter_select("EVIDENCE_LEVEL", "Evidence level",  : 
  argument 4 is empty
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> <Anonymous>
Execution halted

**Comment by sigven** [comment]
Thanks @ersankose for reporting this. Could you provide the example VCF, the build (grch38/grch37), the config file and the command you use to call?

**Comment by ersankose** [comment]
```
python ~/pcgr-0.8.3/pcgr.py \
--input_vcf single_filtered.vcf.gz \
--input_cna ready.tsv \
/PCGR \
/PCGR \
grch37 ~/pcgr-0.8.3/conf/pcgr.toml \
single --no_vcf_validate --tumor_only --force_overwrite
```
  [https://drive.google.com/drive/folders/1fSAa_FM-VQu0e9i0AXIt-u74PbBxCSnN?usp=sharing](url)
vcf and tsv files included.

Thanks for you attention.

**Comment by sigven** [comment]
Hi again,
Discovered the bug, very stupid mistake (a single comma that should not have been present). Fixed in dev now.

best,
Sigve
