### ISSUE TITLE
Open access datasets

### ISSUE THREAD

**Issue by kokyriakidis** [sigven/pcgr#97]
Hi @sigven !

Do you know where I can find some open access wgs breast cancer data in order to compare them with normal female samples? I would like to test the toll from both sides.

I am interested in both Germline and Somatic.

**Comment by sigven** [comment]
Hi @kokyriakidis,
Thanks for your message. I am afraid I do not have a complete overview here. My suggestion to you is to post the same question at [biostars.org](https://biostars.org), then you will reach a much bigger audience :-)

best,
Sigve
