### ISSUE TITLE
Is it possible to incorporate a link of ClinicalTrials.gov？

### ISSUE THREAD

**Issue by gudeqing** [sigven/pcgr#99]
Hi，pcgr is really an awesome work, and I hope it could go further by incoporating the trial information of a drug from ClinicalTrials.gov database, such as add a link when targeted-drug information available.

**Comment by sigven** [comment]
Hi @gudeqing!
Thanks a lot for your input. I am already in process of harvesting data from clinicaltrials.gov, hopefully I will have this in place for next release (January/February 2020). 

Thanks,
Sigve

**Comment by sigven** [comment]
Hi @gudeqing,

A first pass at retrieval of drugs and drug regimens from ClinicalTrials.gov is in the making:
https://www.dropbox.com/s/bdzs27r60fqv4xp/ct_drugs_cancer_conditions_20200304.tsv?dl=0

This will be included in the upcoming bundle update.

best,
Sigve

**Comment by sigven** [comment]
Latest version (0.9.0rc) includes a section on clinical trials, check it out if you like.
